### ISSUE TITLE
Leave federation out of the example for section 1.2

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#11]
I don't think it's necessary to talk about the federation protocol in the example. The side effects (add object to list of user's likes, add user to list of object's likers) work fine for a single-server scenario, also.

**Comment by cwebber** [comment]
It seems useful to know, to understand how federation does work.  It seems useful to me.

I'm closing this because it *does* seem useful to me, but I also feel like we could easily bikeshed on it; if you feel strongly that this is a mistake, please feel free to reopen.  I'd be happy to talk about it on the call, as well.
