### ISSUE TITLE
Review of the spec

### ISSUE THREAD

**Issue by ghost** [w3c-social/activitypump#125]
I've skimmed through the current specification, and I see a few issues.
- There is authentication between client and server and between servers, but no authentication between users for private messaging (aka "DM").
- There doesn't appear to be any mechanism for what are sometimes called "circles" (Diaspora) or "channels" (Hubzilla). That's is, messaging to a whitelisted group of users in a manner which is cryptographically enforced.
- If files/media are attached there is no permissions model for specifying which users can interact with the content.

So to me this looks like an NSA friendly spec which relies purely upon the broken CA system for authentication. The lack of user to user authentication, combined with bad CAs, could mean that fake user accounts are possible.

To make this less abstract, here's some scenarios:
- I upload some family photos to a server running Mediagoblin. I only want other family members and maybe a few friends to be able to comment on the photos.
- The user wears a device which publishes data as messages which an authorised medical service then subscribes to. These messages should be between the user and the health service, and not be readable by third parties.

**Comment by cwebber** [comment]
First of all, thank you for the feedback!

> The lack of user to user authentication, combined with bad CAs, could mean that fake user accounts are possible.

So, it's an unfortunate situation in present history that nobody agrees on what the "right" way to do authentication is, and this group decided that we weren't going to assign an official way to do things.  Unfortunately, that constrains us in how far we can leverage the features of any particular auth system.

However, there are two possible directions for authentication mentioned in the spec, and I believe the "linked data signatures / http signatures" section is a much more robust direction that can prevent adversaries from "faking" messages from users.  However, as cautioned in the spec, it's also a young direction.
- Ensuring the integrity of messages sent between users, as in terms of "actors on servers".  I think the spec does outline a way it could be done via linked data signatures if you read that.  Again, it's not normative, but we're somewhat restricted in how we can go by timing / circumstance.
- Ensuring the integrity of messages sent between client instances of an actor.  This seems closer to OTR.  See [this thread](https://identi.ca/mediagoblin/note/4N2K1yJTTvuaKJJBfXVGYA) for some conversation about doing something OTR-like, including [mray advocating OMEMO](https://identi.ca/mray/comment/4CGvrVEbTsaWfiIOTnXufA).  I'm interested in such things, but I think we're restricted by present circumstances (of not being able to "decide" the auth direction, as said above) to punting that towards a future extension.  However, I believe it could be done, and I'm again interested.

> There doesn't appear to be any mechanism for what are sometimes called "circles" (Diaspora) or "channels" (Hubzilla). That's is, messaging to a whitelisted group of users in a manner which is cryptographically enforced.

We do support messaging to collections, which can be user defined.  I'm not aware of how Diaspora / Hubzilla do this that's "cryptographically enforced".  So again, we won't be able to get a normative requirement for cryptographic checks because of the limitations we're within, but we might be able to get some non-normative language for this.  Could you explain how Diaspora / Hubzilla use cryptography to ensure the integrity of this?

> I upload some family photos to a server running Mediagoblin. I only want other family members and maybe a few friends to be able to comment on the photos.

We do require verifying the integrity of content, though yes, without signatures, it could be CA compromised if you just go back and look at the original source's content.  Again, if the LDS approach is used as described in the document, this can be much more strongly enforced.

**Comment by cwebber** [comment]
I guess one way to put this is: if someone used the [Linked Data Signatures / HTTP Signatures authentication route, as described](https://www.w3.org/TR/activitypub/#authorization-lds), would that satisfy your concerns?

**Comment by cwebber** [comment]
@bashrc Please see commit d4e77f2.  I've adjusted the text around the "verification" section to make the "checking at origin" part expressed as more of a fallback method, but expressed preference for better methods if available (such as signatures), while clarifying that the document does not normatively prescribe any such method.

How do you feel about this?

**Comment by ghost** [comment]
Even if the authentication between servers and from client to server is good this seems like trying to retrofit security onto something which doesn't start with a permissions model which reflects common messaging use patterns. So a user might want to communicate entirely publicly, partially publicly to a whitelist of recipients or privately one to one. Beginning with expected cases like that would then allow you to come up with an appropriate verification/authentication system which meets those needs.

**Comment by cwebber** [comment]
Okay, well again, given that we're limited in how we can specify auth stuff as described above, it sounds like you aren't going to be happy with any solution.  Unfortunately, that's out of my hands since the group decided to not settle on a sepecific auth direction.
