### ISSUE TITLE
concepts

### ISSUE THREAD

**Issue by ebalder** [w3c-social/activitypump#136]
I had some trouble understanding what exactly are some concepts, a link to a definition section would ease the reading of the document:
- outbox
- actor
- side-client
- interaction effects
- activity
- inbox (not really but for consistency)

what's the exit criteria?

**Comment by brooksn** [comment]
> side-client

Is this from the line discussing exit criteria, ...`and handling side client to server interaction effects appropriately`?  It seems to mean "side effects of the client-to-server interaction." I agree, that should probably be clarified.

**Comment by cwebber** [comment]
Thanks for reading the spec, and the feedback!

Yes, sorry, the "side-client" and "interaction effects" bit was a word ordering error.  I've fixed it.  Thank you!

As for the rest of the terms (activity, actor, inbox, outbox), those are all defined in the document or in ActivityStreams.  We _could_ produce a separate definitions section of the spec, but there's a cost to doing that... it would be redundant, and the document is already quite long, the longest of all the documents produced by the Social Working Group (well of the client/server documents.... ActivityStreams itself is longer, due to many definitions of its own).  I'm not sure it's worth the tradeoff?  I could be convinced otherwise, but I'm leaning towards no.

**Comment by cwebber** [comment]
I appreciate this bug (and for cathcing those word ordering errors) though I think that having a "vocabulary key" is probably not a good idea.  As said before, the document is already very long, maybe too long.  The topics are explained in their various sections; if they aren't clear enough in their explanations, those explanations should be improved, and if a term is mentioned but doesn't link to its definition, we should fix that.  If you see individual cases where those should be handled, let me know!  I'm closing this as the abstract though.

Hopefully #158 will be able to help have add an easier ease-in to this anyway!
