### ISSUE TITLE
Actor discovery

### ISSUE THREAD

**Issue by jaywink** [w3c-social/activitypump#140]
The spec needs clarification on how, as a third party server, user profiles (Actors) are discovered, or at least it didn't make it clear to me what is the endpoint that will be hit to fetch the Actor AS2 object.

Is it the Actor ID itself?

**Comment by cwebber** [comment]
Yes, it's the actor ID itself.  Actors are just a type of Object.

We should probably make this more clear... I think the descriptions are split between the (poorly named) [Methods on Objects](https://www.w3.org/TR/activitypub/#obj-methods) section (which should probably be named "Retrieving Objects", since it now only specifies GET and all the POST / etc stuff was moved out of there) and the [delivery](https://www.w3.org/TR/activitypub/#delivery) section.  The "delivery" section probably leans a bit too heavily on Linked Data Notifications... it's great that we know how the overlap between those specs works now, but you shouldn't have to read _another_ spec just to understand ActivityPub.  I'm thinking of moving the Linked Data Notifications stuff to a "relationship to other specifications" appendix.

So I think I should probably do the following things:
- Rename "Methods on Objects" to "Retrieving Objects"
- Clarify in the Actor section that actors are just a type of Object, and are retrieved by their ID just like any other Object.
- Clean up the Delivery section to make it clear enough to stand on its own without _necessarily_ having to read Linked Data Notifications.

Does that sound like it would be useful / make sense?

**Comment by cwebber** [comment]
Oops... it's so easy to accidentally close an issue in github... reopened, since that wasn't intentional.

**Comment by jaywink** [comment]
The last of the three commits you did I think adds the necessary clarification I was looking for, thanks.
