### ISSUE TITLE
Update Activity replacement rule ambiguity

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#147]
7.2 Update Activity states:

> For client to server interactions, updates are partial; rather than updating the document all at once, any key value pair supplied is used to replace the existing value with the new value.

It's not clear to me what happens if a key has a JSON object as its value. Is the entire object replaced (i.e. no recursion into objects)? Presumably so, but better to clarify this in the spec explicitly.

**Comment by cwebber** [comment]
You're right, this is unclear.  Personally, I really don't like the "update individual fields" thing, but this was added to bring us closer to Micropub... though now that we don't think we're merging the specs, maybe it's less important.  Anyway, I agree, it has to be only that this works one level deep... imagine if you have a field that has a list of json objects, and you were replacing a value in one of _those_!

Here's what I'm going to do: I'm going to move the rule about partial updates its own subsection and mark it "at risk".

I know pump.io does some of this now because JanKusanagi tested it.  I'm not sure what's done there.

**Comment by cwebber** [comment]
I clarified that updates are only for top-level fields.  Thanks for pointing this out.

I've also marked that section at risk.  We can thus choose whether we want to support partial updates during implementation experience in CR.

**Comment by rhiaro** [comment]
I totally want to support partial updates.

My use case is clients that do _very specific *things, including
extensions, should be able to happily touch only the bits of an object they
know about without accidentally wiping the rest. *Without_ having to fetch
and blindly potentially store and resend the unknown parts of the object.

**Comment by cwebber** [comment]
Understood @rhiaro.  Is it satisfactory to you to update only toplevel key/value pairs?  I think doing recursive updates is problematic, for the above discussed reasons.

**Comment by rhiaro** [comment]
Definitely, I can't see any of my implementations nesting anything, as you
might imagine.

**Comment by cwebber** [comment]
@rhiaro Seems like the existing answer should be fine then.

And if we have good implementation experience, "at risk" stuff of course can be kept... it sounds like we have good reason to believe that should be fine with the current wording then.  We'll see!
