### ISSUE TITLE
HTTPS-only identifiers is too restrictive

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#15]
Requiring *only* HTTPS identifiers, or null, is excessive.

Additional requirements on identifiers, beyond being URIs, is excessive. In particular, it obviates the use of HTTP identifiers and Webfinger acct: identifiers, both widely uses in pump.io-compatible servers.

**Comment by cwebber** [comment]
I think HTTPS only is important if we're using OAuth 2.0 bearer tokens, and right now that's what we have.  (One can debate that, and I think we should, but I won't here!)  Since there's no signatures, it's really dangerous to go over HTTP only.

That said, it's useful when doing development on localhost to permit HTTP only.  Maybe permitting HTTP can be restricted to localhost only.

**Comment by akuckartz** [comment]
:+1: (but https *should* be used for privacy reasons.)

**Comment by elf-pavlik** [comment]
I hope everyone noticed that Webfinger mandates HTTPS a **MUST**?

https://tools.ietf.org/html/rfc7033#section-4.2
> A client MUST query the WebFinger resource using HTTPS only.  If the
   client determines that the resource has an invalid certificate, the
   resource returns a 4xx or 5xx status code, or if the HTTPS connection
   cannot be established for any reason, then the client MUST accept
   that the WebFinger query has failed and MUST NOT attempt to reissue
   the WebFinger request using HTTP over a non-secure connection.

**Comment by evanp** [comment]
@elf-pavlik HTTPS is great for the public web, but it takes time and is overkill for some situations -- such as in enterprise networks or in private deployments. We can easily use a SHOULD and MAY phrasing to say that you SHOULD use HTTPS and that clients or servers MAY ignore identifiers with protocols that aren't encrypted.

**Comment by akuckartz** [comment]
@elf-pavlik A specification can refer to Webfinger without requiring HTTPS. Otherwise we would unneccessarily duplicate that detail of the Webfinger spec.

**Comment by cwebber** [comment]
Okay, I'm fine with @evanp's wording, I'll try to work that in.

**Comment by melvincarvalho** [comment]
http +1 -- widespread adoption, millions or billions, standardized
https +1 -- widespread adoption, millions or billions, standardized

other uris -- im skeptical, case needs to be made, preferably with implementation statistics

Additionally, hash URIs SHOULD be used, to delineate the difference between document and data.

Otherwise you end up with people called index.html etc. which is going to break a bunch of stuff.

**Comment by cwebber** [comment]
I think hash URIs are optional but aren't required.

If people are named index.html, that's too bad, though I think they're more likely to be named `http://foo.example/u/person/`.  I'm not sure what condition would end up in people mistakenly named index.html

**Comment by jaywink** [comment]
:+1: for HTTPS being SHOULD. Otherwise we'll have libraries which will give you the finger if you try HTTP with them :P

**Comment by cwebber** [comment]
I adjusted the wording in fa38a67 making HTTPS URIs the only scheme explicitly mentioned, but it does not block the *possibility* of Webfinger or HTTP URIs.
