### ISSUE TITLE
[Question] How exactly do comments on shares get distributed?

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#150]
Given a scenario where:
1. Alice and Bob follow each other
2. Carol and Dave (who are on different remote servers) follow Bob
3. Alice posts a note which is distributed to Bob
4. Bob shares the note and comments on it (both of which are distributed to Alice, Carol and Dave)
5. Carol comments on Alice's post shared via Bob

How does Carol's comment reach Alice and, more importantly, Dave? I'm looking at 8.1 Targeting and I can't quite wrap my head around how it works... it _seems_ like it works via notification targeting, along with the fact that addressing is copied to new related objects; is this correct?

**Comment by cwebber** [comment]
It's covered, but yeah, not clear.  I'll add an example to clear this up.

**Comment by rhiaro** [comment]
Hey so I think the spec has been rearranged a bit since this issue was opened a year ago xD

In any case, I added a new section heading [Client Addressing](https://w3c.github.io/activitypub/#client-addressing) (but haven't changed any of the actual content) to make sure it's super clear how Carol's comment reaches Bob's followers. There's already an example to this effect in this section.

Basically Client Addressing rules state that when Carol creates her note `inReplyTo` Bob's share (which would be an `as:Announce` with the `object` of Alice's note), Carol's client *should*\* copy the original audience from Bob's share - Bob's followers collection - and add it to the `to` field of of Carol's note. This means that when it lands in Bob's inbox, Bob's server knows to forward it to Bob's followers collection, because it meets the [three criteria for inbox forwarding](https://w3c.github.io/activitypub/#inbox-forwarding).

\* this is a *should* because implementations may give Carol the chance to delete Bob's followers from the audience if Carol doesn't want the note to be shared so widely, or otherwise handle addressing in some specialised way.

**Comment by cwebber** [comment]
Seems like a smart reworking which adds some clarity.  Since the SHOULD was already in the previous text this is restructuring and not a normative change, so I'm good with it!
