### ISSUE TITLE
Public content delivery

### ISSUE THREAD

**Issue by jaywink** [w3c-social/activitypump#156]
Something that hit me while reading through the delivery part again, which would be a clear blocker for servers like Diaspora, Friendica, etc.

ActivityPub currently specifies delivery to happen to each target actor's inbox directly. While this works, it's hardly optimal when you have multiple users on the same target server. Now I'm talking only about public content here, not content in a limited scope to say an actors followers only.

5.6 defines "Public addressing". It doesn't define any special delivery to be used, in a federated case. Lets take an example of the largest known Diaspora server which currently reports 324929 users. It would not be possible, even if the actors were known, to deliver to each individual user directly.

The Diaspora protocol defines a server specific delivery route (hardcoded as `/receive/public`) that all public content is sent to, which means publicly addressed pushed content can be sent once per server and it will be available to all users on that server.

The problem I see with adding this kind of mechanism to ActivityPub is that it doesn't really define server discovery methods. Diaspora has this route hard coded, which is far from optimal when you want to support whatever kind of application stacks that define their own endpoints. Some kind of discovery process would be needed, for example a `.well-known/activitypub` document etc (just an example, not suggestion).

What do you think, could ActivityPub define public content delivery and possible server discovery documents, or will we need an extension for this? In my experience, in the Diaspora protocol world, most content _is_ publicly addresses. This also holds true for many other networks, largest of them Twitter, where all content is public. So ActivityPub imho needs to provide a way to federate public content between servers, not just servers to actors.

Ping @annando from Friendica who might find following this topic interesting.

**Comment by cwebber** [comment]
_Edit:_ Okay this response is maybe useful to read, but I misread your post at first... the next comment addresses your post better than this one, if I understand right.

Hoo boy!  Yeah that's a chewy topic.  So let me respond in bullet points, since this is pretty complicated.
- First of all, a ha-ha-only-serious response: hey, delivering to one inbox at a time is good enough for email.  Why can't it be good enough for your social network? :)
- Yes, the fan-in/fan-out decision making is complicated.  (I hear it's even complicated for large proprietary social networks.)
- You _could_ kind of do this, by just giving all users the same inbox on the same server and then having the server split addressing itself.  However that means you lose `bcc`.
- There's a feature not currently discussed for delivering to each user's individual inbox, though I've been pretty quiet about it: ActivityPub, as it currently exists, could be used for a peer to peer system, not just a federated one.  In a peer to peer system, _you don't have_ the concept of individual servers, but you do have endpoints, and URIs could  technically use different schemes than http(s).  We'd lose that in this direction.
- Do we really want to optimize for mega-instances?  Isn't that exactly the direction we want to discourage for self-hosting if we can make it happen?

That said, I can sympathize with it.  I can't see how we can put it in place without making things pretty crazy complicated though.

I'd be interested in hearing what @evanp would think of this one, since he ran what afaik is the largest federated-social-web network (and especially largest server w/ identi.ca) that ever existed back in the StatusNet days...

**Comment by cwebber** [comment]
@jaywink Oh, wait, we're talking about public delivery only.  Okay!  Actually I think this is a bit simpler.

In ActivityPub there are _two_ special groups that kind of hit this space.  There's [the special Public group](http://w3c.github.io/activitypub/) (aka `https://www.w3.org/ns/activitystreams#Public`), and then there's a single actor's [followers collection](http://w3c.github.io/activitypub/#followers).

Let's see an example of this:

```
{
  "@context": ["https://www.w3.org/ns/activitystreams",
               {"@language": "en"}],
  "type": "Like",
  "actor": "https://dustycloud.org/chris/"
  "name": "Chris liked 'Minimal ActivityPub update client'",
  "object": "https://rhiaro.co.uk/2016/05/minimal-activitypub",
  "to": ["https://dustycloud.org/followers"],
  "cc": ["https://e14n.com/evan", "https://www.w3.org/ns/activitystreams#Public"],
}
```

Let's look at each of the addresses, and what they do:
- `https://dustycloud.org/followers`: This is my followers collection, so I dereference this collection and send it to all the people subscribed to me.
- `https://e14n.com/evan`: I also send it to Evan.
- `https://www.w3.org/ns/activitystreams#Public`: This one doesn't actually send it anywhere!  It gets marked as being "publicly accessible", which means my server knows that no matter the access control, anyone can see this.

I'm not sure if Diaspora does the same thing.  Anyway, marking something Public alone doesn't send something anywhere, which is why Public is usually grouped with Followers (but not necessarily).  Does that make sense?  (So in other words, marking something Public _doesn't_ send to every user on a server.)

But I think what you mean is that you want a "public timeline" to be visible on each server.  Is that right?  In that case, yes, it would be useful for every server to have a Public endpoint... though of course this Public Timeline would only be between servers that know about each other...?

**Comment by cwebber** [comment]
(Note that, assuming I got it right, it's complicated to do a "server-public" endpoint anyhow, because the SocialWG group decided collectively to not support `/.well-known` in favor of a "follow your nose" traversal approach...)

**Comment by cwebber** [comment]
It also sounds like we're not doing the thing you fear (sending 324929 notices, or to all users on every instance, since we do it by subscribers).  So maybe we've clarified that we've sidestepped what, yes, would have been a big bug.

So I think the "add a server-public endpoint" so there can be a general public timeline is maybe at that point a request for a new feature?  (Maybe we could do this via an extension?)

Does that sound right to you?

**Comment by annando** [comment]
When sending public messages, Diaspora (and Friendica when it transports stuff to Diaspora servers) is collecting the server addresses of the followers and reduces them to the server name. Then it transports a single item to each server (signed with the private key of the sender). Since the receiving server does know the subscriptions of its users, the further delivery can proceed without a problem after the signature was checked.

When doing a non public transport, the items are delivered to each single receiver. Additionally every single transport is encrypted with the public key of the receiver. (And - AFAIK - additionally signed with the private key of the sender)

If you want to have a further look: http://diaspora.github.io/diaspora_federation/index.html

**Comment by cwebber** [comment]
Thanks @annando, that's very helpful.

So to review, ActivityPub still doesn't forward to "public", so you won't end up with the "forward to everyone on earth! (or at least that server over there)" scenario.  But yes, if you attach your followers, a post from a very popular person could send out a ton of duplicate replies over the network.  So this _could_ be a useful optimization.

What are our options?
- `/.well-known` can be done, but it violates the Follow Your Nose behavior desired by the group.
- But maybe we could put an endpoint in the [endpoints](http://w3c.github.io/activitypub/) section, something like `publicInbox`.  This wouldn't be per server.... but multiple users on the same server could presumably share the same public inbox, and thus a server could be smart about "condensing" them down to that same single endpoint.  We could do this and mark it "at risk".
- Taking we could take either the `.well-known` or `publicInbox` approaches and punt this to an extension, if it seems useful enough.

What do you think?

**Comment by rhiaro** [comment]
So I guess this could work as an extension, in that some servers can advertise a 'multiInbox', ie. a place to send stuff if you notice that it's addressed to many users on the same server. Sending servers support it by noticing that they're about to send to a bunch of inboxes with the same root domain, and look for that domain's publicInbox to send it there instead. But if the receiver doesn't have a publicInbox the sender can still fall back to individuals. And if the sender doesn't know how to look for a publicInbox, it can fall back to sending to individuals anyway.

So if something hits the multiinbox, with a million addressees (because the sender noticed some of those were on the same server), then the multiinbox can read all of those, and forward it _internally_ to the inboxes of the ones that belong to it.

It wouldn't necessarily be readable in the same way that a normal Inbox is. More an endpoint for internal optimisation.

**Comment by annando** [comment]
Could you point me to the part of the discussion where this "/.well-known" stuff was discussed? I would like to understand the reason behind the decision behind - and what "follow your nose" is meant to be.

The idea with the additional endpoint sounds like a working solution when "/.well-known" isn't the preferred way.

BTW: Concerning the addressing: When we would send a message to that endpoint: Do we have to address the separate receivers in "to", "cc" or "bcc" or would the server know whom to deliver the message?

**Comment by cwebber** [comment]
@annando This conversation happened a longggg time ago, at the second face to face at MIT.  You can [read the meeting logs here](https://www.w3.org/wiki/Socialwg/2015-03-18-minutes).

So you've got a few types of URLs for endpoints...
- _URL Patterns:_ Well, you know that this application has `/u/<username>/` for users, so you basically hardcode that _every_ site uses `/u/<foo>/` just like that site.  Kind of silo'y.
- `/.well-known/`:\* You've got pretty much just one root place to start looking up URL patterns.  As Evan points out, there's some good reasons to want it in terms of having to do less lookups.  
- _Follow your nose:_ You just follow URLs to find where to go.  You get an actor URI, you don't drop the path off the URI and start hunting around for something magical on that domain, you look at that document you were pointed to and use its own links to start figuring out where to go.  (This also has the nice property in that it's not restricted to HTTP(S) as a URL scheme.  It's also much more "linked data"'y.)

I guess [follow your nose is defined here](http://patterns.dataincubator.org/book/follow-your-nose.html).  I dont' know the origin.

As it turns out, webfinger uses the well-known pattern, but it can get away with this because we have a URI schema for webfinger now, so we can kind of use that as a hack to both have webfinger and do follow your nose.

Anyway, that's an attempt to give some history.  It was pretty early on when all this discussion was happening for me.

**Comment by cwebber** [comment]
So I've thought about this some more, and it's clear to me at this point that this is an optimization aimed at "large federated sites".  While I think a better federated web ends up less on the "large federated sites" end, it might be worthwhile, since things seem to often not end up that way (for a whole basket of yet-unsolved deployability isssues).

Yet at the same time, I think this issue came in too late to consider thoughtfully before we hit CR.  We could try to rush in a property, but I'm not sure we'd get it right, and we could add a lot of complexity to things.

Luckily, it's not the end of the world: we have an extension mechanism (thanks json-ld!).  We _can_ revisit this at a future time, and since it's effectively an optimization, it's not necessarily a blocker for the spec to get it out there.  I'd be interested in exploring it being an extension at a future time.

But for now, I think we can't get it done with the level of thoughtfulness and care required at the moment.  So I'm marking this as being postponed for the future.  It's not off the table... it can be done as an extension, or maybe even in the (possibly unlikely?) chance that we get another working group together to do another AP revision, but I think it won't happen here.

I still think this has been useful feedback to capture and refer back to though!  I really do appreciate it.  And I'm interested in exploring it if people want to work with me into the future.

**Comment by annando** [comment]
"follow your nose" and a missing public endpoint both doesn't sound very promising to me. Since Friendica is a multi protocol system it uses especially the content in `/.well-known` to distinguish between the different networks. Not having a `/.well-known` path on a server will be a problem. Additionally with a missing webfinger support and - if I understood it correctly - no support for a user@domain.tld format, I guess I will wait for future changes before implementing it.

**Comment by jaywink** [comment]
High fever put me out of action for a few days - seems things "resolved" pretty quickly.

I'm not sure rushing things will get us to the best possible target. But if it's the deadlines that are important then I understand it's too late to discuss. I do disagree heavily that the federated web has to mean each person runs their own instance. That is simply unrealistic. For this spec to help make the web decentralized it _must_ also address the needs of large sites which want to integrate with single individuals, small sites and other large sites. Right now this spec is really only targeting single individuals or very small sites integrating with each other. This is not necessarily the fault of the working group but the lack of input from all of the federated social web.

Anyway, back to the subject. I do agree a `/.well-known` document is not the best idea for this spec. The reason is there is no concept of server, which the well-known really requires. A person might be running their instance under a sub-path or on a shared instance with hundreds of other sites - and no control over the root path. This is what makes this different from say the Diaspora protocol, which is very much based on the server concept (and also limited to some extent by it).

With an extension we could bring necessary support on top, that would make it possible to use ActivityPub in more use cases. This could be the "common inbox" talked about here in a few comments. It could also preferably be a reference to the server itself which would just be another AS2 object with its own id. So, an `Actor` would reference the server id with some extension attribute and the server object would then be fetched, containing various useful information about itself (like where to send public content). This would support "follow your nose" and of course supplying a server ID would be a total MAY.

This would enable servers to interact which each other as well (for public content delivery, for example). but they would still be found through the actors on them and direct user to user actions would work through the core spec.

**Comment by cwebber** [comment]
Reopening this for discussion.

@annando I understand your desire for `/.well-known/`.  As I said, webfinger _is_ supported because there's a URI scheme available for webfinger, which gets around the problem.  But I think @jaywink is right in his description; the "server" here is a bit more vague.  And `/.well-known/` does create problems for people who want to run multiple federated systems on the same domain... you can't run diaspora and pump.io (or pump.io and mediagoblin, etc) on the same domain.

We could try to get in a `multiInbox` feature.  If someone can describe the functionality in summary clearly enough, and it doesn't seem like it would be buggy, we can add it and mark it at risk if we have time.  Again, I don't think it's a blocker for the feature if we don't... the extension route is open to us.  But I'm leaving this open for the moment.

**Comment by jaywink** [comment]
@cwebber I think you forgot to click the "reopen" button ;) Anyway, here is my proposal for an implementation which I think is very simple and **totally** not mandatory for anyone to implement but it would remove one blocker from implementing networks like Diaspora, Friendica, etc. It's not a complete "paste in and go" but just some basics that can be used, if felt good.

How I would be able to use this as an implementer. When fetching actors, any found server ID's would also be resolved at the same time, locally saving their public inbox endpoints. Then when delivering publicly targeted content, the endpoints can be used directly, just like it works now for example in Diaspora and Friendica.

---

# Servers

Servers in ActivityPub are objects themselves, represented by an HTTP URI. An ActivityPub server can be thought of an owner for Actor objects. Actors MAY define a server by using the attribute `server` containing the ID of the server.

There is no one URI namespace for server objects. Also, servers are not limited to "one per domain". This is why server objects should be discovered through their actors and stored for later, if necessary.

## Server objects

Server objects are ActivityStreams objects of `Actor` class with the type of `Application`. In addition to the standard attributes, ActivityPub adds the following
- **publicInbox** - An ActivityStreams `Collection` comprising of all the publicly targeted activities the server knows about. This endpoint accepts POST and is where publicly targeted activities can be posted when targeting the whole server. As a side effect of receiving publicly targeted activities in the public inbox, the server MAY make these activities available in the inboxes of actors it owns.

### Example server object

```
{
  "@context": "https://www.w3.org/ns/activitypub",
  "type": "Application",
  "id": "https://example.com/",
  "publicInbox": "https://example.com/publicInbox.json",
  "name": "Example Server"
}
```

### Example of an Actor defining a server

```
{
  "@context": "https://www.w3.org/ns/activitypub",
  "type": "Person",
  "id": "https://johnsmith.example.com/",
  "following": "https://johnsmith.example.com/following.json",
  "followers": "https://johnsmith.example.com/followers.json",
  "inbox": "https://johnsmith.example.com/inbox.json",
  "outbox": "https://johnsmith.example.com/feed.json",
  "preferredUsername": "johnsmith",
  "name": "John Smith",
  "summary": "Just an example guy",
  "icon": [
    "https://johnsmith.example.com/image/165987aklre4"
  ],
  "server": "https://example.com/"
}
```

**Comment by cwebber** [comment]
Oops, I did forget to reopen it.

@jaywink Thanks for this!  I think it has the right idea, but I think we can reduce the machinery while providing the same functionality even further.  We [already have an endpoints field on actors](http://w3c.github.io/activitypub/#endpoints) which are usually endpoints shared by actors on a single server anyway (but not necessarily).  Anyway, we could just put the `publicInbox` in here and then there's one less hop to a server definition.  Servers can reduce delivery to users across who shares the same `publicInbox`.  (Btw, I _really_ like the point that publicInbox can also be a readable OrderedCollection.  Great point!)

On the flip side, maybe it's nice to have a machine-readable description of a `Server`... but given that we could reduce the size of the ActivityPub document by a bit (which is already large) by not adding an extra section for servers, I think it might be nice to just do it in the `endpoints` section.

What do you think?

**Comment by jaywink** [comment]
While the `Server` object could be useful, I do tend to think premature optimization should be avoided unless we can identify real cases for it. If the `publicInbox` is fine in the endpoints of the actor then I'm totally fine with that. It's simpler, less chance something unnecessary is introduced into the spec and will work for this use case. :+1:

**Comment by cwebber** [comment]
Okay, I'll draft something fusing the ideas we've put down here and mark it at risk.  Thanks for your feedback :)

**Comment by cwebber** [comment]
Ok @jaywink, I added text which I think satisfied our above conversation.  Could you review?

**Comment by jaywink** [comment]
@cwebber awesome, looks good to me :+1: Added one commit comment just regarding terms used.

From my part this can be considered as not a blocker any more and can be closed. What do you think @annando ?

**Comment by rhiaro** [comment]
@cwebber, couple of things about what you have so far:

If the sender has to do a GET on every recipient to see if they have a `publicInbox`, isn't this just as burdensome if there are a million? Would the optimisation be to check the root domain? But perhaps this isn't possible, as the root could be a directory anyway, and you wouldn't be able to figure out what it is.

> use its own following lists to determine

I think perhaps "use its own internal mechanism to determine" ?

**Comment by jaywink** [comment]
@rhiaro as an implementer for server software that is designed to deal with thousands of users on a single server, I would certainly cache the Actor objects for at least some time anyway. Retrieving them every time would be a serious performance drain, whether delivery is to each individually or via the `publicInbox`.

If the sending server caches the Actor objects it can internally handle the reducing of deliveries without having to always fetch all possible Actors that could be targeted.

**Comment by cwebber** [comment]
@jaywink is exactly right... I expect that implementations would have cached representations of an actor's profile in any case where there's a subscription involved.

If you aren't doing that, then you probably shouldn't use `publicInbox`.  It's an optional feature that acts as an optimization between implementations that know how to use it.

**Comment by cwebber** [comment]
I'm also going to say that unless @annando objects, if @jaywink thinks this is good (and is the original submitter), I think we're probably good.  @annando, feel free to raise objections and I'll happily reopen if it turns out you've found issues.

**Comment by annando** [comment]
I would of course use cached representations. Question is if these values are defined as static. It would be a problem if - for example - the "publicInbox" value would change from time to time.

Everything else sounds totally fine.

**Comment by cwebber** [comment]
@annando I don't think `publicInbox` is likely to be a property that changes much.  Also if a server has a subscribed user, they'll _hopefully_ get updates to that user's profile

But yeah you're right, caching challenges will be an issue here and even everywhere... but I think that comes with the domain. :)  Hopefully we can try to get as much delivered through subscription mechanisms as possible, where you can be told when things change.

**Comment by annando** [comment]
Question is if it could be written down in the standards that these values mustn't change over time.

**Comment by cwebber** [comment]
While cache invalidation is a valid concern, "fixing" the profiles to specific points might also be problems.  I feel I'm not confident enough to add such a requirement.

I don't _think_ it'll come up in practice much though... I can't imagine implementations changing these fields often anyway?  But they might, for good reasons (and hopefully the publishing system will inform other nodes of updates)... so I don't want to say they MUST NOT change them.
