### ISSUE TITLE
Notification Targeting: is it complete and is it secure?

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypump#161]
https://w3c.github.io/activitypub/#targeting

> Notification targeting ensures the owners of all linked objects are notified of a new Activity that relates to them. Thus, the target(s) for delivery of an Activity may be:
> 
> Primary targeting: the values of the to, cc or bcc fields (likely to include the followers collection)
> Notification targeting: the actors for all objects in the object, target, inReplyTo or tag fields

~~In AS2, the domain of the 'actor' property is said to be only 'Activity'. The class of Activities is disjoint from the class of Objects. i.e. 'actors for all objects' doesn't make sense to me in the context of AS2 as objects cannot have actors.~~
Edit: I was just plain wrong about the disjointed sets. I was confusing with Objects vs Links. Sorry, and thanks for correcting me @rhiaro 

~~Furthermore and similarly, 'inReplyTo' and 'tag' have a Domain of Object, and not Activity.  i.e. 'all objects in the ..., inReplyTo or tag fields' doesn't make sense to me in the context of AS2 assuming by 'fields' you mean 'fields in the Activity'.~~
Edit: This concern is gone because Activity subclasses Object

It's not clear to me how you intend an implementor to implement Notification Targeting, nor whether what you intend is complete enough for what I hope it facilitates.

So let me elaborate on what I hope targeting/delivery could facilitate. Let's look at Create activities and Like activities. Let's say an Activity coming into an outbox was:

``` json
{
  "type": "Create",
  "actor": "https://rhiaro.co.uk/",
  "object": {
    "type": "Article",
    "url": "http://pastebin.com/posts/my-better-way-of-writing-specs",
    "tag": ["http://schema.org/Recipe"],
    "inReplyTo": "http://pastebin.com/posts/how-to-write-a-spec"
  }
}
```

If all relevant remote servers were sufficiently capable, I'd love for the following use cases to be possible as a result of delivery to other servers:
- Notify the root activities' .actor's inbox, so that actor can show a single activity feed of their actions on their site
- Notify the .objects.tag(s) inboxes so that the pages describing those tags can link back to things recently applying the tag
- Notify the .object.inReplyTo's inbox so that that webpage can show a list of replies

``` json
{
  "type": "Like",
  "actor": "http://bengo.is",
  "object": {
    "url": "http://pastebin.com/posts/my-better-way-of-writing-specs",
  }
}
```
- Notify the .object.url's inbox so that Article can show a list of federated Likes below it
- Notify the .object.attributedTo's inbox so that author can maintain a stream of all Likes of their works  
  - If the Like activity above were submitted as above, this would require dereferencing the object URL. Or maybe if it were sent to the object.urls's inbox, that inbox could be required (or SHOULD) to forward to the object's .attributedTo

So... to be more than just critical of the current draft, what if instead of 

>  Notification targeting: the actors for all objects in the object, target, inReplyTo or tag fields

it was something like:

> When an outbox receives an Activity, it MUST forward it to the inboxes of the activity's actor, object, target, instrument, origin, result (these are the properties in AS2 whose Domain is an activity). If that Activity is a "Create" activity, it MUST be forwarded to the inboxes of any property of the newly created Object (e.g. inReplyTo, tag, attributedTo)
## 

Related Security Concern, perhaps orthogonal and already exists in the spec, but I am confused enough about the current "Notification Targeting" text that I don't want to create a second issue quite yet.

I'm tempted to also propose a clause in there that implies: "The activity should not be forwarded to a target unless it is addressed (via to, bto, cc, bcc, or audience) to that target, or the activity is addressed to the Public Collection". i.e. just because I create something that is inReplyTo something, doesn't mean I want that something (or its author) to be able to see it.

**Comment by rhiaro** [comment]
> In AS2, the domain of the 'actor' property is said to be only 'Activity'. The class of Activities is disjoint from the class of Objects.

`Activity` is a subclass of `Object`, not disjoint. 

> i.e. 'actors for all objects' doesn't make sense to me in the context of AS2 as objects cannot have actors.

But I think it's true that an `Object` that isn't also an `Activity` shouldn't have an `actor`, yeah.

> Furthermore and similarly, 'inReplyTo' and 'tag' have a Domain of Object ...

I think that's fine due to subclassing.

**Create example**
1. The client generating the `Create` Activity fetches (with discretionary recursion depth) `object`->`inReplyTo`->`attributedTo` and adds that value to the `Create`'s `to` field, per [client to server interactions](https://w3c.github.io/activitypub/#client-to-server-interactions).
   - it should do the same for `tag` though it's not clear for a schema.org one how the tag would be attributed. It needs to publish some short of ownership using AS2 to be AP-compatible. Tags on my site are `Collections`, which would work.
2. The client then posts the `Create` to the `actor`'s _outbox_ (not inbox). The outbox is the feed of all their activity on the site.
3. Upon hitting the outbox, the _server_ is responsible for re-sending this Activity to anyone in the `to` field, per [outbox delivery](https://w3c.github.io/activitypub/#outbox-delivery).

**Like example**

I'm not sure what we do with `url`... I think this should be `id`, otherwise it's not a valid object. And if it's `id`, then steps 1. and 2. of the previous example should do what you want.

>  If that Activity is a "Create" activity, it MUST be forwarded to the inboxes of any property of the newly created Object (e.g. inReplyTo, tag, attributedTo)

This is totally how I thought it was supposed to be working, and there are probably commits from me from August where I was trying to write this up.

> just because I create something that is inReplyTo something, doesn't mean I want that something (or its author) to be able to see it.

This is ultimately why we shifted from what you just proposed as text (and how I thought it should be) to making the addressing the _client_'s responsibility. With current pumpio clients, they figure out the addressing and display it to the user with an option to edit it before the user hits send. So the client can do sensible automatic addressing and then the user can go ahead and say "I don't want that" and override it before. This of course depends on UI and implementation specifics, but the way the spec is worded now presents the _possibility_ for the client to let the user have more control over this.

@cwebber might have more to add, and probably remembers me going to through this exact same thought process on multiple occasions in August..

Obviously this isn't clear though, so we should work on some editorial updates to make it so.

**Comment by rhiaro** [comment]
> Notification targeting: the actors for all objects in the object, target, inReplyTo or tag fields

Basically it's used in the third bullet of [inbox delivery](https://w3c.github.io/activitypub/#inbox-delivery) for the AP equivalent of salmentions, and it only happens if all three bullets are true. It's there to catch cases where the creating server's outbox couldn't deliver somewhere because the client didn't have eg. read access to a collection of actors reached via one of these properties (so couldn't add them to `to`), so they have to offload it to a server which does have read access.

**Comment by gobengo** [comment]
@rhiaro Thank you for fast clarification.

I get it now, that the client must explicitly address and the server doesn't need to infer much. And in fact, this is what 8.2.1 Outbox Delivery describes.

So I re-read to try to understand where I got confused. It's in here:

> 8.1 Targeting
> Primary targeting is per the audience targeting properties from the [ActivityStreams] specification. Notification targeting ensures the owners of all linked objects are notified of a new Activity that relates to them. Thus, the target(s) for delivery of an Activity may be:
> Primary targeting: the values of the to, cc or bcc fields (likely to include the followers collection)
> Notification targeting: the actors for all objects in the object, target, inReplyTo or tag fields
> If the entry is a collection, then the server must dereference the collection (with the user's credentials) and discover inboxes for each item in the collection. Servers must limit the number of layers of indirections through collections which will be performed, which may be one.

"Notification Targeting" as a term isn't used anywhere else in the spec in a normative way. Also, right after it's described here, there's language about what a _server_ needs to do to be clever about targeting. And in fact, what it describes isn't really consistent with the maxim of "The Client should address, not the Server".

I think this also sort of deals with all my concerns about use cases being fulfilled, as again, it's up to the client to populate the audience properties it wants to target. So I retract that proposal.

Other than this editorial suggestion about Notification Targeting clarity, I could close this issue. Feel free to, or I will if conversation on that front stalls.

Thanks Amy

**Comment by rhiaro** [comment]
Sorry, I've just been making updates to my previous comments. I should have realised you'd be reading this in real time :) And I feel like I'm explaining terribly. So I'm glad that helped. Pretty sure we need a diagram.

**Comment by rhiaro** [comment]
> "Notification Targeting" as a term isn't used anywhere else in the spec in a normative way

You're right this is I think an artifact of an earlier iteration. We'll see if we can clear this up a bit more.

**Comment by rhiaro** [comment]
> And in fact, what it describes isn't really consistent with the maxim of "The Client should address, not the Server".

yeah, this is to catch the case where the client could not explicitly address because of access control on objects or collections

**Comment by cwebber** [comment]
Good discussion!  I'll try to clear up the terminology around "notification targeting".

I agree that it's confusing as it is; it's not clear enough what the distinction between targeting and delivery is.

**Comment by cwebber** [comment]
I removed the legacy "notification targeting" text, which was indeed an artifact before we clarified that the client determines recipients.  I also merged "targeting" and "delivery" into one section.

@gobengo Does this look good to you?

**Comment by gobengo** [comment]
Yah, good change Chris. Closing.
