### ISSUE TITLE
Ignore should maybe have a side effect?

### ISSUE THREAD

**Issue by strugee** [w3c-social/activitypump#182]
Possibly too late for this (and I'm not 100% sure this should be a thing), so feel free to close, but it seems like an AS2 `Ignore` activity should maybe have a side effect similar to that of `Block`, but causing the user's inbox to not return activities by the ignored user. Note that this is different from `Block` because while `Block` mandates that the blocked user can't interact with any objects posted by the blocker, that doesn't say anything about the blocked user directly addressing activities to the user (or indirectly addressing activities to the user by e.g. commenting on a post shared by someone the blocker follows).

**Comment by cwebber** [comment]
It's a good idea, but it's probably too late in the game to add this.  It will probably have to go into an extension document.

**Comment by rhiaro** [comment]
We could make this a MAY..

**Comment by cwebber** [comment]
The group talked about this on the call; Tantek pointed out that the fact that we're considering this as a MAY shows that it's also a good fit for an extension... since we haven't had much time to incubate this, this will be good extension territory.

(Evan also pointed out that it's most important that we already have Block, since in their experience not having Block by the time you hit federation can cause problems re: dealing with abuse, etc (so in that sense, we're already ahead!) but that muting is a bit less critical.)

It's a good call anyway... look forward to it as an extension. :)
