### ISSUE TITLE
No mention of caching

### ISSUE THREAD

**Issue by AstraLuma** [w3c-social/activitypump#190]
No where in the specification does it mention the user of underlying transport (HTTP) caching. Namely, servers should respect it when talking to other servers, and servers should implement the cache control mechanisms (eg 304 Not Modified), as specified by the underlying transport (eg, HTTP/1.1, HTTP/2)

This is especially true for Actor object, where server configuration (inbox/outbox URLs) is mixed with user data (name, summary), so having to make multiple network requests for every option is sub-optimal.

This is exacerbated by the public Inbox algorithm, where you must 1. Discover the public inboxes for all targets, 2. Compile a list of inboxes to actually submit to, 3. Submit to the identified inboxes.

(Servers _may_ change their endpoints at basically any time, when software changes or if they move to a new implementation. Or part of a hare-brained security scheme.)

**Comment by strugee** [comment]
I'm guessing too late to make normative changes (beyond a MAY at least) and I don't know that that would be the best anyway since the fact that AP generally relies on HTTP implies you're implementing HTTP according to the HTTP standard. But this does seem useful to add a non-normative note for? @cwebber?

> 304 Not Modified

This is the only HTTP caching method I can think of that's usefully applicable to ActivityPub, since as you noted Actors include user data that could change at any time. So it seems to me that you can never completely avoid a round-trip to the server to confirm that something isn't stale. Does that seem correct to you @astronouth7303?

**Comment by AstraLuma** [comment]
Well, if the remote server specifies time-based caching, the requesting system should respect that. This allows for individual providers to make decisions balancing propagation delays with load (since the Agent information changes infrequently and I don't think it's a problem if it takes time to show up on remote systems). In summary: HTTP/1.1 and HTTP/2 have several cache mechanisms; please use them.

There's also the off-spec cache heuristic available under linked documents: If the cached URL returns a 404/410/etc, re-request the cached document that we got the URL from.

**Comment by AstraLuma** [comment]
Or: I don't think a normative specification is required, just a note/reminder that the underlying transports may have caching mechanisms defined, and implementations should respect and use them.

**Comment by strugee** [comment]
Ah right. Cool. (I wasn't suggesting we should actively decide on a subset of HTTP caching to recommend implementations support, just thinking out loud.)

**Comment by sandhawke** [comment]
Yeah, seems reasonable to give people some helpful pointers on caching and mention that it's polite and often required for acceptable performance.  That way we can avoid using normative sounding language (like "should").
