### ISSUE TITLE
Actor is not a profile object. 

### ISSUE THREAD

**Issue by PaulJeong14** [w3c-social/activitypump#213]
I’m very confused of below statement :

> 4. Actors 
> Actors are [ActivityStreams] Objects, generally one of the ActivityStreams Actor Types or a Profile object,

In the Activity Vocabulary, Actor’s definition is :

> Actor types are object types that capable of performing activities. 

And profile object’s definition is : 

> A Profile is a content object that describes another Object, typically used to describe Actor Type objects.

The statement of activitypub does not comply with the definition of Activity Vocabulary.
Precisely, actor is an object performing activities and profile object is an object to describe the actor. 
They are clearly different. 

So, it's better to explain about the Actor that Actor can have profile object to describe itself.

**Comment by cwebber** [comment]
Heya @PaulJeong14... well we were trying to clarify things, but maybe we just made them more confusing?  What's intended to be conveyed is that in ActivityPub, every activity flowing across the wire has some "actor"... but what objects are acceptable for that?  Technically nothing in ActivityStreams mandates that it has to be one of the Actor Types AFAIU, and we're saying here that someone can have a sub-identity with all the usual ActivityPub inbox/outbox/etc endpoints on it, which can fit in the Activity slot.  Perhaps @jasnell or @evanp can clarify whether it's acceptable to have a Profile object under the "actor" slot of an Activity, but I think that Evan at least must be fine with it, because they were involved with the discussion to add Profile there last week.

However, I agree it's confusing, since we now have two definitions of what Actor is... one of the official "Actor Types" or a Profile.

My impression is though that the current set of actor types are just that, a set of possible likely candidates to fill that role, and it's expected that it's even possible for other types to fill there that aren't in the ActivityStreams "Activity Types" list... especially if they are types that come from extensions.

Does that clarify anything?  It's possible that the addition of Profile there isn't of significant benefit though and it just confuses the section, in which case I don't have any objection with removing it.

**Comment by strugee** [comment]
Perhaps we can restructure the sentence to be something like:

> Note that ActivityPub actors don't necessarily have to be subclasses of Actor in ActivityStreams. For example, a Profile object may be used as an actor, or a type from an ActivityStreams extension.

**Comment by strugee** [comment]
Or maybe even better:

> ActivityPub actors are generally subclasses of Actor in ActivityStreams, but they don't have to be. For example, a Profile object might be used as an actor, or a type from an ActivityStreams extension.

**Comment by cwebber** [comment]
@strugee I really like that!  I'll change it to say that.

@PaulJeong14 does that resolve this for you?

**Comment by cwebber** [comment]
@strugee oops except it brings back the subclasses bit, and the Actor superclass doesn't exist anymore.  Here's a fix: 

> ActivityPub actors are generally one of the ActivityStreams Actor Types, but they don't have to be. For example, a Profile object might be used as an actor, or a type from an ActivityStreams extension.

**Comment by strugee** [comment]
I'll do the PR

**Comment by PaulJeong14** [comment]
ok. It is fine wih me.
