### ISSUE TITLE
there is no explanation about subscription.

### ISSUE THREAD

**Issue by PaulJeong14** [w3c-social/activitypump#214]
in the abstract section : 

> as well as a federated server to server API for delivering notifications and subscribing to content.

but there is no explanation about subscription in the server to server API section.

So,  how about changing that statement like below:
> as well as a federated server to server API for delivering notifications and content.

**Comment by cwebber** [comment]
There is discussion of subscription:

        <h3>Follow Activity</h3>
        <p>
          The <code>Follow</code> activity is used to subscribe to the
          activities of another user.
        </p>

**Comment by cwebber** [comment]
But perhaps "subscribing to content" is not clear, since it's a very specific form of subscription in here, specifically the followers mechanism.  We don't really have any other subscription systems.  So perhaps the text should be adjusted to say that.

I agree that the text is pretty awkward, and I think dropping "subscribing to" is a good call.
