### ISSUE TITLE
Controlling availability to search

### ISSUE THREAD

**Issue by sandhawke** [w3c-social/activitypump#221]
**More general discussion moved to https://github.com/swicg/general/issues/3**

Earlier today someone released a search engine for mastodon and the response included several concerns.

See thread: https://freeradical.zone/@Balor/146643

Breaking this down a little:

Would it help to have a way to indicate whether items (including people/accounts) are intended to be included in search results?   Does this connect to robots.txt?   

Alternatively, is it feasible to have a kind of loose access control, where content can be available to most of the people who'd see it anyway (the original audience and everyone it gets boosted to), but not to unwanted folks who come along later, including search engines.

I'm tempted to quote and archive the comments in the thread linked above, but ... that might violate the privacy intent of those posts.  It would be great if this issue could be addressed in a broad way that helps solve that problem.

**Comment by cwebber** [comment]
Note that we sort of have something, since we have a special Public collection.  If you haven't addressed your post to the Public collection, it probably isn't viewable on any public timeline.

There may be some other reasons to express intent though.  It's tricky territory.

**Comment by nightpool** [comment]
## it's not about availability, it's about context

collecting here some of my earlier toots on the situation:

> the thing to understand here is that, by adding full text search, all conversations are now happening in a public space FOR THEIR KEYWORDS. Hashtags are the opt-in solution here, using t/e/x/t l/i/k/e t/h/i/s is the opt out one. It's not about my toots being publicly available, it's about people being able to search "trans" and my rants about gender stuff, meant for a specific context, showing up divorced from ALL context

> I think [that's the] important difference between public by default and full text search. It's one of context. I'm fine with people seeing my public posts in the context of my timeline or a public timeline. But when the only context is their keywords, that's what causes problems.

> C.f. the discourse around bookmarking sites and tags, which is what hashtags grew out of, or read some of the posts from around the time where tumblr changed between tag search and full text search

and some stuff from chat:

>`nightpool` Also like, as a moderating voice here about robots.txt stuff, I find Google et al search to be MUCH less harmful then Twitter/real time/time ordered search
>`nightpool` Because it's completely unordered.
>`nightpool` So its not going to lead to immediate real time harassment in the same way that Twitter search does.
>`nightpool` And because it returns SO MUCH it doesnt lead to the negative social effects Tumblr search has (where signal is really high and people get mad at noise)

so those are the key points for me.

**Comment by nightpool** [comment]
Key takeaways: search should be opt-in, using specific keywords. Hashtags are already a *great* mechanism for that, although there's not a lot of sugar for them on Mastodon right now, so that's a bit of a barrier to adoption (filtering people's timelines by hashtags, filtering hashtags by date, etc)

And I think that that the issues of whether someone can, e.g., search my posts on their own, or google my posts, are all separate issues here. I have my own preferences on those (yes, search my posts if they're already on my page, yes google my posts), but other people have different opinions too for various reasons.

Whether or not people agree about making their posts searchable in general, full-text search across all toots will *always* have negative outcomes compared to opting-in to certain keywords (using tags)

**Comment by jaywink** [comment]
How would Activitypub be able to control anyone from not indexing public content? By the very definition of the word "public", if the author has set that visibility to the whole world, they should expect anyone to also be able to not just view it, but index and analyse it.

We could *recommend* not indexing any content, but that would not stop anyone from doing so. The only real way for authors to control their content is to not dispatch it to a public audience. (though of course even then it depends on whether the receiver respects your privacy choice - but that is another whole matter that can't be controlled)

**Comment by nightpool** [comment]
@jaywink just because something can't be controlled doesn't mean the protocol shouldn't support it being suggested. social factors are bigger then technical ones.

I'm not sure how you get to "well we can't do this one thing because people might not respect it" to "they should use this other feature that people also might not respect instead". That seems to be an inconsistent. I believe in both search and privacy settings built into protocol, but it seems like you believe in neither (or at least that your arguments work equally well for both)

**Comment by cwebber** [comment]
We can support it effectively as an advisory flag to not index.  I know @nightpool thinks the preference should be to "opt in", but I think "opting out" would actually be a more reliable flag for bots to notice, especially because this is a more specific "by default" norm for certain communities.  This would be easy to accomplish in mastodon as an opt-in anyway: by default, mastodon always sets the "no index" advisory flag, unless the user chooses to enable indexing.

It's true that it's advisory; you have to trust that something will listen to it.  It's basically the robots.txt of federation.  You can't trust it to stop bad actors, but you might get good and well-informed actors to listen.  (In fact there's every chance that abusers could use the presence of such a flag as an additional method to determine who to target, and that's not possible to stop.)  But maybe it's still worth it.  Though there's a danger: selecting this on/off in the UI might even give the impression to users that they're *protected* in some way from unwanted indexing, so a UI should provide a clear warning if they implement it.

If we add this, it's a bit tricky as to whether to do it as part of core or as an extension.  Do it as core, and we might flub it given the short time we have left.  Do it as an extension, and implementors of various services might not be aware of it.

**Comment by nightpool** [comment]
@cwebber To be clear—I don't think it's as simple as index/not index. I want people to be able to search my posts, but not see my posts in the context of a full-instance search. Or people should able to see all of my "#stucky" posts across the entire instance, but I don't want people searching on other terms that come up in that post, if they're not included. That's the distinction I'm trying to draw, between just opt-in indexing and opt-in **keywords**.

one's just about availability, one is a much more subtle point about *placing your posts in an intentional social context*. If you haven't been on a site like tumblr or a bookmarking site that has an out of band "tags" mechanism, this may be a strange way of thinking about things to wrap your head around, but it's ultimately the core of all of the problems with full-text search.

I don't like robots.txt specifically because of it's inflexibility. It's not just about what people can index—it's about what they can index it for. Also it lumps all "automated" things into the same category, even when they have vastly different purposes—wayback machine is blocked next to google is blocked next to followbots.

**Comment by cwebber** [comment]
> I don't like robots.txt specifically because of it's inflexibility. It's not just about what people can index—it's about what they can index it for. Also it lumps all "automated" things into the same category, even when they have vastly different purposes—wayback machine is blocked next to google is blocked next to followbots.

Hm... there are indeed a lot of reasons to pull content from a public timeline.  Search, whether via tags or full text, are possibly just one of them.  Another could be to get a sense of what topics are interesting, or develop a "if you followed X, you might like to follow Y" type system.  I'm a bit worried we won't be able to anticipate all that.

We could leave a space for "I'm okay with this and not that and etc" but as someone who's seen a lot of ontology wars, it makes me pretty nervous that it's going to fall over...

**Comment by nightpool** [comment]
I agree. I think it's more useful to provide for *affordances* for things
we want to encourage, such as opt-in keywords for searching, then to
provide for further and further grains of restrictions we require clients
to implement.

a "do not index this" flag is probably ALSO useful, but it doesn't really
capture what's different about full-text search vs. hashtag search. Many
users are okay with one, but not the other, and there's a very important
reason as to why (all of the stuff I said above). I think that as said
above, a "do not show this in search results EVER" flag is basically
provided for by the "Public" address though.

(*whispers* i'm just saying.... maybe we could use a tags field.....)

**Comment by cwebber** [comment]
> (*whispers* i'm just saying.... maybe we could use a tags field.....)

We do already [support tags in ActivityPub via ActivityStreams](https://www.w3.org/TR/activitystreams-vocabulary/#microsyntaxes), fyi!

**Comment by nightpool** [comment]
ah, thanks, I was confused because activitystreams requires a tag to be an object,
and I couldn't find a relevant object type. personally I really prefer the tumblr format, where tags aren't part of the content proper and are completely standalone metadata, but this is an acceptable compromise.

**Comment by cwebber** [comment]
@nightpool The tag is separate metadata, though it might be referring to something inside the content (and usually is extracted from it, but that's doing by the server).  See the example from that linked section:

``` json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "name": "A thank-you note",
  "type": "Note",
  "content": "Thank you <a href='http://sally.example.org'>@sally</a>
      for all your hard work!
      <a href='http://example.org/tags/givingthanks'>#givingthanks</a>",
  "to": {
    "name": "Sally",
    "type": "Person",
    "id": "http://sally.example.org"
  },
  "tag": {
    "id": "http://example.org/tags/givingthanks",
    "name": "#givingthanks"
  }
}
```

So here it's the list of things under "tag".  Hope that helps!

**Comment by nightpool** [comment]
@cwebber right—I was referring more to the specific example of a hashtag (I saw the example) where it's something extracted from the content. I'm happy to hear that it works for standalone metadata as well. I'm concerned that there's no type of object for it and kind of confused about how it works if we're talking about searching on it—how do we distinguish it from other types of tags? (tagging someone in an image, for example, or an at-mention)

**Comment by cwebber** [comment]
@nightpool [Mention](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-mention) has its own type.  So normal tag you'd use a simple [Object](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-object) or a [Link](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-link).  Want to at-mention someone or etc?  Use `Mention`.

**Comment by sandhawke** [comment]
@nightpool I appreciate your efforts to explain this, but ... can you make it more clear for me?  You say

> C.f. the discourse around bookmarking sites and tags, which is what hashtags grew out of, or read some of the posts from around the time where tumblr changed between tag search and full text search

but I don't know how to find that discourse or those posts.  If you read them and remember them, perhaps you could construct a search that would turn up a few key ones.  (The keywords "tumlr" and "tags" are pretty useless, and I'm not finding anything that seems relevant.)

I can see how there might be negatives to people having their posts seen outside of context, but how is that any different from google's search results show snippets out of context?   In either case, seeing a snippet is clearly not enough to really understand it, and in either case users should be able to click through and see the context.

You say there's a timeliness issue, but I'm having a hard time imaging a threat that is prevented by delaying indexed 24hrs or something.

And it's not like we can just follow you advice, avoid the downsides I'm not quite understanding, and everything will be okay.  There is a lot of value in powerful, complete, real-time search.  If we don't provide that, we reduce the value of the system, we reduce its ability to be useful to people, and we reduce the appeal of decentralized social vs the silos.   Frankly, I'd really like to have feature parity with the major silos, plus the decentralized features we like.

Probably what would be most helpful is if you can tell a couple stories about bad things that have happened because of full text searching.   When we get into the details of the stories, it may turn out that the harms can be mitigated in other ways, eg by how the search results are presented, or what one sees on clicking through to more details.

**Comment by sandhawke** [comment]
Maiyannah Bishop (postActive lead dev) writes:

>@sandhawke @cwebber @vhf @balor I'm strongly against having Advisory fields because they offer a false sense of security.  Anything without enforcement can safely be assumed to be ignored by a bad actor.      -- https://plateia.org/notice/97440

(and then says she'd rather not post it on github herself, but that I'm welcome to.)

**Comment by nightpool** [comment]
I was going to type up a long oral history of the use of tagging in fandom, but I realized one already exists for me: http://idlewords.com/talks/fan_is_a_tool_using_animal.htm (mostly the first half is relevant to this discussion)

The downsides of full-text searching have been explained much, much better by people who have vastly more experience in it then me, but unfortunately most of my knowledge of it is first hand: having people come into my conversation on Twitter just because I happened to drop the name of a company or a hot-button issue. So I don't have any links to places of further study. Full-text search is a huge vector for harassment and abuse.

**Comment by nightpool** [comment]
(sorry, made some substantial edits to that post—anyone contributing by email is invited to check the updated version)

**Comment by sandhawke** [comment]
(or who is looking at the web page.  github does not give any indication that a comment has changed after being displayed.   I was confused for a while after reading the pinboard story.  It was a good story, at least.   As it turns out, the first half is all stuff I knew.   In fact, I traced the history of fandom and slash for one of my fascinated kids a couple days ago.)

Firsthand stories are the best, IMHO, because then one can have a real conversation about the details.

From what you're saying, it sounds like you think the problematic people who would jump into your Twitter conversations has low-to-medium resources.  Some people have bot armies and would be perfectly capable of searching everything and ignoring advisory flags; those would be high-resource threats.   But the kind of people you're talking about are not that.  You're talking about folks who are bored or drunk or something and just search some keywords and react with hostility as soon as they see your posts.    

Is that right?

**Comment by nightpool** [comment]
@sandhawke yeah, that's a good summary of why I think it's useful. High-resource threats in this sense are generally very rare.

Another good example would be companies that track mentions of their names. They are a type of actor that would be unwilling to transgress explicit social norms (ignoring advisory flags) but are perfectly happy transgressing unwritten ones (jumping into the middle of conversations if you happen to summon their name). There are other types of actors who fall into this category, like people who are invested in maintaining a good reputation.

**Comment by sandhawke** [comment]
Yes, thanks, those make sense.

So, then how do we square this with Maiyannah's concern that it will give users a false sense of security?

I guess careful wording and UI design.

How would you phrase this flag?

  [ X ] Request that systems hide this from public search results

I'm not sure that quite covers the folks-tracking-their-names issue, because they might well be running their own engine.    Maybe:

 [ X ] Do not circulate.  Flag this post as intended for my regular readers only.   It should not be returned in public search results, and comments from strangers are not welcome.

Something like that?

**Comment by nightpool** [comment]
As I said above, I don't think a flag is the right way to address this issue.

**Comment by nightpool** [comment]
(although I think "Request that systems hide this from public search results" is ALSO a useful flag, it's just not the one that addresses this particular issue specifically)

**Comment by sandhawke** [comment]
Sorry, I'm lost.   What's your proposal, then?   The current spec, by saying nothing, seems to make it fine to write search engines.    Are you suggesting the spec should tell people not to?   Or let them know that if they do, they might be doing more harm than good?   Or that there be a lore associated with the spec, but not written in it, that if they implement public search people will be annoyed?

**Comment by nightpool** [comment]
I don't have any specific suggestions for the spec, other then that maybe
the documentation around tags should be more explicit about
tags-as-metadata and not just generated data, and maybe include a
first-class tag type for "category" or something similar that could serve
the purpose of a "searchable text field". I was just attempting to give a
thorough grounding of the issue for those interested in discussing it.

**Comment by nightpool** [comment]
here's an example:

```json 
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "name": "Some musings on searchability",
  "type": "Note",
  "content": "Maybe the text content of all posts *shouldn't* be immediately searchable.
   Although, how would one find the post suggesting that?",
  "to": {
    "name": "nightpool",
    "type": "Person",
    "id": "http://nightpool.example.org"
  },
  "tag": [{
    "type": "Category",
    "name": "search meta"
  },
  {
    "type": "Category",
    "name": "....maybe too meta for my own good"
  }]
}
```

would be one possible expression of an ontology I think would be useful in avoiding full-text search. (by giving something concrete to search against instead, the sum of all Category tags)

**Comment by evanp** [comment]
This is what audience targeting is for. If you want to distribute to the public, target the public. If you don't, target a group, a list, individuals, or your followers.

**Comment by evanp** [comment]
If it's important to have a way to distribute publicly, but not be searchable, make a new well-known target that is PublicNotSearchable. Sending to that will go to /dev/null if it's not understood, or to the right destination if it is.

**Comment by cwebber** [comment]
I don't think any concrete proposals came out of this thread.  I'd like to close it.  @sandhawke are you okay with that?  This seems like a conversation for the SocialCG tracker if anything.  (And since we [do have an issue there](https://github.com/swicg/general/issues/3) I think it should be fine?)

**Comment by sandhawke** [comment]
I suppose, yeah, no clear path forward right now.

**Comment by till** [comment]
Hello :wave: — I hope it's alright to comment here (else, please let me know) despite it being closed.

I came across this topic after talking to a friend about what's currently possible and what not, and why not.

My experience with ActivityPub is solely based on Mastodon currently though I understand that the same/similar structure/objects can be used for other experiences.

Having said all this, [a lot of Mastodon instances](https://docs.joinmastodon.org/user/preferences/#misc) provide the user with the ability to select a `noindex` thing when they create an account or later in the profile settings. If I get it right, this setting is currently used for the web experience to tell crawlers if content can be indexed or not.

Now to the actual question: how feasible is it to add this setting to all objects created and exchanged during federation? It would seem that if the changes are made in Mastodon (and others server implementations) to make this field opt-in (as in `noindex` is the default), it would satisfy concerns that users have to be index or not. Instead of relying on tags (that may change or may be different across languagess), I envision a property of `no-index` could be added like so:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "name": "Some musings on searchability",
  "type": "Note",
  "content": "Maybe the text content of all posts *shouldn't* be immediately searchable.",
  "no-index": true,
  "to": {
    "name": "nightpool",
    "type": "Person",
    "id": "http://nightpool.example.org"
  },
  "tag": [{
    "type": "Category",
    "name": "search meta"
  },
  {
    "type": "Category",
    "name": "....maybe too meta for my own good"
  }]
}
```

On an implementation level this could be done according to what the user selected in their profile, or even be changed with the client on a case-by-case basis. Additionally, an instance implementation which supports this should elevate this in capabilities (similar to e.g. length of posts, etc.) so it could be used as an indicator if it's safe(r) to peer with another instance who doesn't support it.

Thoughts?

**Comment by TallTed** [comment]
@till — For good or ill, compliance with `noindex` is voluntary. There is (to my knowledge) no technical way to prevent indexing, other than preventing browsing by entities (typically identified by browsing history, IP address, Agent signature, among other characteristics) you believe are only browsing to crawl & index, which may also inadvertently prevent browsing by entities who are just surfing and who you *want* to see your data...

**Comment by till** [comment]
> @till — For good or ill, compliance with `noindex` is voluntary.

Yeah, like `<meta/>` and `robots.txt`. I am aware of it not being a barrier.

I am looking for a way though to add the information to posts to federate it.
