### ISSUE TITLE
What is the relationship between OStatus, pump.io and ActivityPub?

### ISSUE THREAD

**Issue by lofidevops** [w3c-social/activitypump#228]
My understanding is that:

* **OStatus** is a decentralized social networking protocol made up of several other protocols (Atom feeds, Activity Streams, PubSubHubbub, Salmon, and WebFinger)
  * *GNU Social* and *Mastodon* are two server software applications that implement OStatus
* **pump.io API** is an interface to the pump.io server software (Activity Streams, OAuth, Web Host Metadata)
  * *identi.ca* is a pump.io instance (not accessible right now), *GNU MediaGoblin* is a server application that currently uses a pump-like API
* **ActivityPub** is a proposed decentralized social networking protocol
  * *GNU MediaGoblin* is a server application that will likely implement ActivityPub

How do these protocols interoperate? Does ActivityPub completely replace OStatus, or only the Activity Streams component?

Cross-posted: https://stackoverflow.com/questions/44546232

**Comment by lofidevops** [comment]
Reading https://www.w3.org/TR/activitypub/#acknowledgements suggests that OStatus, pump.io API and ActivityPub are wholly distinct protocols (with ActivityPub built on lessons learnt from the earlier two). So interoperability would happen at the software layer, not the protocol layer, for example if [Mastodon implemented ActivityPub](https://github.com/tootsuite/mastodon/issues/1557). Have I got that right?

**Comment by sandhawke** [comment]
Yes @kwill .   I can see both sides to that issue.  I think the hope is that AP is enough simpler and easier to work with that people will be willing to add it and eventually let OStatus support atrophy.   That argument sounded a lot more convincing a year ago, before Mastodon took off, for several reasons. Probably the next step is still to see what it's like for Mastodon to implement AP.  I'm particular curious how it might affect visibility of replies, boosts, etc, in practice.  Those semantics are tricky.

**Comment by strugee** [comment]
@kwill I'd also echo what @sandhawke said. To give some more concrete answers to your questions:

> OStatus is a decentralized social networking protocol made up of several other protocols (Atom feeds, Activity Streams, PubSubHubbub, Salmon, and WebFinger)

Yes.

> GNU Social and Mastodon are two server software applications that implement OStatus

Yes, and they interoperate because of that.

> pump.io API is an interface to the pump.io server software (Activity Streams, OAuth, Web Host Metadata)

Correct. You can find details of this at https://github.com/pump-io/pump.io/blob/master/API.md. pump.io is, at its core, just an ActivityStreams distribution engine. It's actually relatively simple because of that, conceptually speaking. You might find [this talk][], given by me, useful. (I'm the primary maintainer of pump.io, though I didn't write it.)

 [this talk]: https://media.libreplanet.org/u/libreplanet/m/pump-io-the-federated-extensible-social-network/

> identi.ca is a pump.io instance (not accessible right now), GNU MediaGoblin is a server application that currently uses a pump-like API

Yes. identi.ca is "just" another pump.io instance, and it will federate with any other pump.io instance. I've forgotten the exact details of where MediaGoblin is (@cwebber would know), but IIRC they currently have a working client-to-server API which is basically the pump.io client-to-server API. They also have plans to introduce federation. This feature has been available in a development branch for a while, and currently federates using the pump.io protocol (there exist demonstrations of MediaGoblin servers running this branch interoperating with regular pump.io servers). However, there are plans to change this feature to use ActivityPub instead.

> How do these protocols interoperate? Does ActivityPub completely replace OStatus, or only the Activity Streams component?

ActivityPub is intended to completely replace OStatus. OStatus is large and complicated (and thus a lot of work to implement). It provides a lot of features that aren't used in practice, and (AFAIK; I'm not an expert in OStatus) its model makes it difficult to do some things. I _think_ Mastodon, for example, has had some problems implementing private messages because of the way OStatus works.

> Reading https://www.w3.org/TR/activitypub/#acknowledgements suggests that OStatus, pump.io API and ActivityPub are wholly distinct protocols (with ActivityPub built on lessons learnt from the earlier two).

They are indeed completely distinct protocols. However, ActivityPub is _very_ similar to the pump.io API/protocol. Conceptually speaking it can be thought of as a slightly simplified version of the pump.io stack, and using ActivityStreams 2.0 instead of the original ActivityStreams spec.

In turn, pump.io's protocol and design was heavily influenced by lessons learnt from OStatus. Evan Prodromou, the author of pump.io, was also the person who wrote StatusNet (now GNU Social), so he had a lot of experience with the pain of OStatus when writing pump.io - OStatus' complexity is one of the reasons pump.io's distribution model is so simple. Again, [this talk][] goes into these details.

Hope this helps clear up some of your confusion.

**Comment by strugee** [comment]
Also, I'm not sure I understand what you mean when you say:

> So interoperability would happen at the software layer, not the protocol layer

Can you clarify what you mean by "software layer" and "protocol layer"?

**Comment by sandhawke** [comment]
I take that to mean that interoperability would be provided by having each server speak multiple protocols.  This is in contrast to having servers able to just implement the protocol they want, but they still talk to each other because the how the different protocols are designed.  That kind of protocol interoperability is great, but it constrains the design a lot; basically you have to keep making things more and more complicated, never simpler, so (as you say) we didn't want to go that way here.

**Comment by lofidevops** [comment]
Thanks so much for the informative answers. (Re. layers, yes I was trying to distinguish between a server speaking multiple protocols, and a protocol that interoperates with other protocols. I'm anticipating a near future where I'm running a server that needs to federate with ActivityPub, OStatus and pump.io servers.)

**Comment by strugee** [comment]
@kwill ah, gotcha. Yes, it interoperates at the software layer, not the protocol layer.

Do note, however, that generally speaking OStatus is considered "legacy" by the Working Group, and we'd like OStatus servers to migrate to ActivityPub. pump.io will be migrating too.

**Comment by nealmcb** [comment]
For the record, Mastodon implemented ActivityPub soon after this discussion.... :smile: 

* [Mastodon launches their ActivityPub support, and a new CR\! \-\- ActivityPub Rocks\!](https://activitypub.rocks/news/mastodon-ap-and-new-cr.html)
