### ISSUE TITLE
"Sensitive Media" tag

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypump#231]
Is there a proper way to mark something as NSFW?  Is this important enough to have in ActivityPub proper, or should it be an extension?

See also [this thread on NSFW in AP + Mastodon](https://mastodon.social/users/Gargron/updates/3244985).

**Comment by nightpool** [comment]
side note: Can we refer to it in discussions going forward as "sensitive media"? (and rename the issue?) NSFW is mostly used as a historical accident, and it has weird implications, is hard to localize, and is rooted in bad workplace culture assumptions (including assumptions about sex work)

**Comment by nightpool** [comment]
Anyway, I think the correct way to do this is to add a "sensitive" boolean property to Image, Video, and Audio. (or perhaps a string ("warning"?) that can contain a specific warning about the content if one exists.)

**Comment by cwebber** [comment]
> side note: Can we refer to it in discussions going forward as "sensitive media"? (and rename the issue?) 

Good call, and done.

**Comment by cwebber** [comment]
> Anyway, I think the correct way to do this is to add a "sensitive" boolean property to Image, Video, and Audio.

Good call, and I think there's no need to restrict it based on object type.  There's all sorts "sensitive" literature out there :)

**Comment by cwebber** [comment]
We're thinking related to #232 there would be a common Content Warning type tag for sensitive media.

**Comment by ghost** [comment]
We had this same discussion about email back in the 80s. A simple boolean wasn't seen as enough information; as some people are sensitive to different things. This wasn't ever implemented but we ended up in general agreement on an enum or tag set which could reference the concepts of soft-nudity, porn, violent content, and religious polarisation. Actually I seem to recall there ended up with about 20-30 categories and a lot of bickering over details and that's likely why the discussion died, but these were the ones that I personally took to be critical. For instance alcohol is offensive to some, but this is often seen by others as a subset of religious polarisation. You also have completely different interpretations of soft-nudity across cultures.

**Comment by cwebber** [comment]
There's strong desire expressed from the Community Group to have this as a new property in ActivityPub, a `sensitive` property which is a boolean.  This can be attached to toplevel objects, or even attachments of images/video etc.

This can be used *in addition to* content warnings, tags, etc.

**Comment by evanminto** [comment]
Should `sensitive` be used alongside `summary` then? Like, `summary` takes on the Mastodon-esque "content warning" connotation when the object is marked as sensitive?

**Comment by nightpool** [comment]
I think that's good semantics

**Comment by cwebber** [comment]
@evanminto That would make a lot of sense to me!

**Comment by tantek** [comment]
Is this just an advisory flag from the author?

**Comment by nightpool** [comment]
@tantek yes, that was the way I understood it.

**Comment by cwebber** [comment]
We had a resolution recently that ActivityPub won't add properties to ActivityStreams that aren't protocol related, so this needs to move to an extension.

**Comment by cwebber** [comment]
[Sensitive property proposed here](https://www.w3.org/wiki/Activity_Streams_extensions#sensitive_property), raising to discuss in next SocialWG and SocialCG calls.

**Comment by ThisIsMissEm** [comment]
> [Sensitive property proposed here](https://www.w3.org/wiki/Activity_Streams_extensions#sensitive_property), raising to discuss in next SocialWG and SocialCG calls.

What was the eventual outcome here? It looks like it's an extension that's used but not documented in any spec or namespace officially.

i think the landscape may also have changed significantly since 2017, wherein publishing sensitive content (especially adult content) to persons under the age of 18 is now an offence that can carry fines & jail time (see age verification bills around the world, Germany, France, several US states, the UK, Australia, etc). These laws actually mandate verifying a user is over the age of 18 (sometimes dubbed the PG-ification of the internet, where everyone is assumed to be a child until otherwise proven)

Back in 2018, for Switter to exist on the fediverse, that instance had to mark all outgoing media as sensitive (as what's sensitive to different groups is contextual, and majority of the content moderation reports were from people seeing adult content in the federated timeline, but it not being marked as sensitive).

There's also now tumblr's new content labelling which seems to be at the behest of Apple, which categorises into Mature or not, and within Mature, several categories (alcohol & drugs, violence & gore, sexual themes).

Given the growth of the fediverse, and the change in the political/legal landscape, is there a need to revisit the definition of "sensitive content"?

Or would this be better addressed through custom audiences or groups? (e.g., users' could mute posts targeting a specific audience, but still get the rest of that users posts that don't include that audience?)
