### ISSUE TITLE
Document `Undo`ing Blocks, and maybe reading back Blocks

### ISSUE THREAD

**Issue by puckipedia** [w3c-social/activitypump#240]
Currently, the spec says nothing about Undos on Blocks. Maybe it's also an idea to have a (private) collection of blocked people, so you can look back who is blocked? (I kinda implemented this in Kroeg already... :P)

**Comment by puckipedia** [comment]
Implementation update: Due to how Undo's work, I replaced the `blocked` collection in Kroeg with `blocks`, which is a list of Block Activities. I still have a `blocked` list internally, but it's blocked (hehe) off so it isn't readable from the user.

**Comment by cwebber** [comment]
Specifying `Undo`ing Blocks seems reasonable.  At least you could say that it undoes the blocking of side effects of future actions.

I think having an actor privately having a `blocked` property makes sense, and indeed I also implement such a collection in ActivityPub.  One issue is that, how do you discover it?  I don't actually have the `blocked` property on my actors because it seems... weird, even if it's a private collection.

**Comment by cwebber** [comment]
I'll make a change along these lines:

```
<eprodrom> "For example, Undo may be used to undo a previous Like or Follow."                                         
           -> "For example, Undo may be used to undo a previous Like, Follow                                          
           or Block."
```

**Comment by cwebber** [comment]
I'll write up some wording for adding a private blocked collection for next week.

**Comment by rhiaro** [comment]
`blocked` and `blocks` collections sound like extensions at this point, what say ye @cwebber? To the CG..?

**Comment by cwebber** [comment]
I think so!  Conversation continued here: https://github.com/swicg/general/issues/23
