### ISSUE TITLE
Content type of server-to-server request bodies unspecified

### ISSUE THREAD

**Issue by erincandescent** [w3c-social/activitypump#256]
Section 3.2 specifies the content types negotiated for responses (the JSON-LD profile mime type, or optionally application/activity+json); section 6 specifies that the JSON-LD profile MIME is to be used in POSTs for client-to-server interactions, but nowhere is a MIME type specified for server-to-server interactions

Section 6 mandates use of `application/ld+json; profile="https://www.w3.org/ns/activitystreams"`. The same should probably be done in section 7.

**Comment by nightpool** [comment]
this was something we ran into while developing mastodon as well. I don't know if we figured out why the spec mandated the ld+json over the activity+json format though—it seems much more inconvenient to parse, and not many http libraries have support for profiles

**Comment by gobengo** [comment]
@nightpool I also took note of that when implementing activitypub for https://distbin.com/
It seems a little more activist than pragmatist for activitypub to more strongly encourage `application/ld+json; profile="https://www.w3.org/ns/activitystreams` when ActivityStreams so intentionally specifies its own media type that doesn't require profile parsing.

**Comment by nightpool** [comment]
I think the thought was that it would be more broadly compatible—I'm just
not sure if that's borne out in practice.

**Comment by akuckartz** [comment]
@nighpool @gobengo I was involved in those discussions in the WG regarding ActivityStreams. The JSON-LD supporters (including myself) were (and are) not convinced that a special Media Type is needed in addition to ‘application/ld+json‘. And those who considered Linked Data to be irrelevant did not like a solution requiring the JSON-LD Media Type. The solution was a compromise.

**Comment by gobengo** [comment]
@akuckartz thanks for the additional insight. I basically agree that a special media type is not needed for AS (ship has sailed though). Just speaking up so that @nightpool knew they weren't the only one who noticed the AS/AP dissonance, nor th eonly one who had to try a few header parsing libraries to find one that parsed the profile parameter correctly.

wrt to this particular issue. I would be in favor of some language that just says:

* Whenever you send or receive ActivityStreams Objects, it should be the same mimeType
* that mimetype should be `application/ld+json; profile="https://www.w3.org/ns/activitystreams"`
* if any clients or servers receiving server2server requests see `application/activity+json` instead, they should treat it as equivalent to `application/ld+json; profile="https://www.w3.org/ns/activitystreams"`
  * ~~maybe the same for `application/json`~~

**Comment by erincandescent** [comment]
Requiring it for `application/json` wouldn't be reasonable - e.g. some implementations (e.g. pump.io) may need to use that for legacy formats

**Comment by gobengo** [comment]
@erincandescent I said 'should', not 'require', but you make a good point nonetheless.
Perhaps an AP implementation encountering `application/json` MAY attempt to treat it as equivalent to AS, or the AP spec just doesn't mention it. I'd slightly advocate mentioning it as it makes a ActivityPub more approachable for non-LD and non-AS2 historians. And that the socialwg (FWIW) charter says to produce a JSON syntax/protocol, which I interpret as 'application/json'.

Even if SHOULD, when/if pump.io supports AS2 and encounters application/json, it could quite easily determine if that JSON is valid AS2, and, if not, interpret as the original pump.io JSON format. In this case I believe it would still be compliant.

**Comment by cwebber** [comment]
FWIW originally we *did* use `application/activity+json` as the default choice.  However we switched it to `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` since that would mean broader by-default interoperability with Linked Data Notifiacations, SoLiD, and other linked data systems (which would otherwise need to hack in a new mimetype).

**Comment by strugee** [comment]
> Even if SHOULD, when/if pump.io supports AS2 and encounters application/json, it could quite easily determine if that JSON is valid AS2, and, if not, interpret as the original pump.io JSON format.

FWIW I (pump.io's primary maintainer) would definitely be against this change. Too hacky and for, AFAICT, no good reason.

**Comment by gobengo** [comment]
alright, I struck that out of what I wrote above as it's distracting from the point of this issue

**Comment by strugee** [comment]
@gobengo you're right, sorry - my bad for commenting on a tangent :P

**Comment by rhiaro** [comment]
I'm 99% this commit https://github.com/w3c/activitypub/commit/31ad3477c7c6cf928f2126c542ddc6f9855ac08d resolves the original issue, but would appreciate review

**Comment by cwebber** [comment]
LGTM!  I'm removing the "waiting for commenter" flag (since I think this satisfies the rough consensus of the thread and since I did review.)  Thank you Amy!

**Comment by nightpool** [comment]
@rhiaro @cwebber why was this marked as editorial? it adds a new MUST for implementations (and should probably be reflected in the implementation reports, at the very least)

**Comment by rhiaro** [comment]
Did the omission of this line mean implementations were done differently? I marked it as editorial because (due to the other references in the spec) I thought this was just an oversight and that implementations were using consistent media types already, so they woudln't actually be changing.

**Comment by nightpool** [comment]
@rhiaro Mastodon currently uses `application/activity+json` everywhere for s2s federation and is now out-of-spec.

(all of our accept headers specify both though)

**Comment by cwebber** [comment]
I suppose that's true; previously this being unstated meant that we assumed everyone was interpreting the content type requirements as being the same as it was for client to server.  From *my* perspective, this was simply a textual ommission, since I thought the previous statement of the mimetype also covered server to server and it was simply a spec error that it hadn't been said elsewhere.

In another section of the spec we say:

>  The HTTP GET method may be dereferenced against an object's id property to retrieve the activity. Servers MAY use HTTP content negotiation as defined in [RFC7231] to select the type of data to return in response to a request, but MUST present the ActivityStreams object representation in response to application/ld+json; profile="https://www.w3.org/ns/activitystreams", and SHOULD also present the ActivityStreams representation in response to application/activity+json as well. The client MUST specify an Accept header with the application/ld+json; profile="https://www.w3.org/ns/activitystreams" media type in order to retrieve the activity. 

We should put this same SHOULD of application/activity+json as well here and that would apply the "robustness principle" for receiving server-to-server content, meaning in general Mastodon's use of activity+json will be understood.

**Comment by cwebber** [comment]
@nightpool said on IRC that cb6297a61f73bb614d1b6e65e7bb3c26b5e9a5ef was good enough to resolve this for them, so closing!
