### ISSUE TITLE
how about changing 'ActivityStreams' to 'ActivityVocabulary'.

### ISSUE THREAD

**Issue by PaulJeong14** [w3c-social/activitypump#257]
This is not for the implementation but for the editorial stuff to clarify more. 

In the section 1. Overview,

> ActivityPub uses [ActivityStreams] for its vocabulary. This is pretty great because ActivityStreams includes all the common terms you need to represent all the activities and content flowing around a social network. It's likely that ActivityStreams already includes all the vocabulary you need, but even if it doesn't, ActivityStreams can be extended via [JSON-LD].

I think it's not  'ActivityStreams'  but 'ActivityVocabulary' which provides terms and definitions. 
So, I think it's better to change 'ActivityStreams' to 'ActivityVocabulary. 
what do you think about that?

**Comment by nightpool** [comment]
>The Activity Streams 2.0 Vocabulary defines a set of abstract types and properties that describe past, present and future Activities.

**Comment by cwebber** [comment]
I think "Activity Vocabulary" is way more confusing.  It's the vocabulary of "Activity Streams", which is what everyone knows that vocabulary as.

**Comment by akuckartz** [comment]
:-1:

**Comment by sandhawke** [comment]
@PaulJeong14 I agree that for coming to this stuff fresh, the naming you're suggesting would probably make more sense.  But the reality is that ActivityStreams is an existing standard that's fairly well known in this space and can't practically be changed at this point.   ActivityPub kind of has to work around that. 

The text you're commenting on is taking some linguistic shortcuts, which might add to the confusion.  The first sentence might be rewritten like this:

> ActivityPub builds on [ActivityStreams] by re-using its syntax, data modeling, and vocabulary for its data exchange needs.  ActivityStreams 2.0 Core provides a general structure and vocabulary for describing activities, while the ActivityStreams 2.0 Vocabulary provides ways to describe common online activities, including those related to publication. Because of this structure, ActivityPub is able to simply reuse ActivityStreams 2.0 as its own data format.

Does that help clarify the situation?

**Comment by strugee** [comment]
Or if we wanted to keep it short we could also simply change

> ActivityPub uses [ActivityStreams] for its vocabulary.

to

> ActivityPub uses [ActivityStreams] for syntax in conjunction with the associated [Activity Vocabulary].

**Comment by cwebber** [comment]
ActivityStreams doesn't really provide syntax much on its own though.  It's just a vocabulary with JSON(-LD).

**Comment by gobengo** [comment]
@cwebber That's one way to look at it... but as we're all too familiar with the editor went to great pains to make it more than "just a vocabulary", but instead a well-defined syntax even if you don't know JSON-LD. In fact, while I am a fan of JSON-LD, my AP implementation did not need to use it until I wanted to fully support LDN pings with other vocabs.

From the Intro of spec:
"It is the goal of this specification to provide a JSON-based syntax that is sufficient to express metadata about activities in a rich, human-friendly but machine-processable and extensible manner."

And section 2:
"This specification describes a JSON-based [RFC7159] serialization syntax for the Activity Vocabulary that conforms to a subset of [JSON-LD] syntax constraints but does not require JSON-LD processing."

I think it's accurate and politically pragmatic to say ActivityPub gets its syntax from AS2 (and is therefore also compatible with JSON-LD)

**Comment by PaulJeong14** [comment]
ok, I agree with Sandro's explanation that ActivityStreams can be changed practically in this space.
let's close this issue.

**Comment by sandhawke** [comment]
@PaulJeong14 you mean "can't", right?

**Comment by cwebber** [comment]
> a well-defined syntax even if you don't know JSON-LD.

Note that I said JSON(-LD) ;)

**Comment by sandhawke** [comment]
I'm not sure what you mean with the smiley.   JSON has a syntax.  JSON-LD also has a syntax; it happens to be a carefully designed subset of the syntax of JSON.  ActivityStreams also has a syntax; it happens to be a carefully designed subset of the syntax of JSON-LD.  Three distinct formal languages, which are successive subsets (sublanguages) formed by adding constraints on the syntax and semantics. Right?   

As I understand it, AP end points have to support the AS syntax, so that AP consumers don't have to have full JSON-LD processors.   Am I wrong?   I can't find anything in the spec that speaks to this, but it seems implied by the content-type paragraphs. The first sentence of the abstract strongly implies it, too, but "based on" could be meant in some loose sense.

**Comment by nightpool** [comment]
@sandhawke I think @cwebber was just saying he tried to use the parentheses to convey that nuance

**Comment by cwebber** [comment]
@nightpool has it right.

This is a bit off topic, but for clarity of what I mean: as for what "syntax" means separate from "vocabulary", I tend to think of JSON and JSON-LD as "syntax", since they are the structure of the objects being represented.  For the most part, ActivityStreams defines what those objects mean as a vocabulary *within* both of those structures.  For example, [Hy](https://hy.readthedocs.io/en/stable/) is a lisp-y "syntax" of Python... they share *nearly* all the same vocabulary, but one uses a whitespace-significant syntax while the other is parenthetical.  However, syntax does convey some other things too, such as ordering of elements: you could say that the expectation that we expect the Create activity to wrap some other Object is syntactic, but I think it's stretching it a bit.  You could also wrap ActivityStreams in n-quads and I think, to me, that would be a completely different syntax conveying the same vocabulary.

I don't think that's important to resolving this issue, but there you have my thoughts on it...

**Comment by PaulJeong14** [comment]
@sandhawke I mean "can't". sorry for mistake :-)

**Comment by sandhawke** [comment]
No problem, thanks
