### ISSUE TITLE
Public collection URI gets compacted into as:Public

### ISSUE THREAD

**Issue by puckipedia** [w3c-social/activitypump#264]
`https://www.w3.org/ns/activitystreams#Public` is inside the `as` namespace, so compacting a JSON-LD document with this data turns it into... `as:Public`

aaand now my JSON-LD compacted output can't be understood by clients that assume only `https://www.w3.org/ns/activitystreams#Public`

**Comment by cwebber** [comment]
So this isn't technically "wrong", but it's something existing implementations are probably unaware of, which is indeed a problem we need to handle.

We can add a note to the spec declaring that implementations which are reading data sent across the wire as "just json" should also be aware that `as:Public` is also a valid way to specify the Public collection.  However this means that we should contact existing implementations and be sure that they implement support for this behavior.

This seems to me to be the cleanest path forward... does it seem that way to others too?

**Comment by cwebber** [comment]
Checked in a note to the spec in 66cf356 ... would appreciate review.  Is this good enough to close this?

I also added https://github.com/tootsuite/mastodon/issues/5551 ... would be good to open issues in other AP project repos as well.

**Comment by cwebber** [comment]
If someone is willing to review/ack, I think we could close this... what do people think?  @puckipedia especially, since they raised it :)

**Comment by rhiaro** [comment]
A couple of things..

* The 'as' prefix is just an arbitrary string; if someone happened to make their implementation use a different prefix, it would be compacted as something else.
* It's also possible for someone to set the `@context` to `https://www.w3.org/ns/activitystreams#` then represent it simply as `Public`, which is what my implementation does (if you ask for `activity+json`, not if you ask for `ld+json`).

We could get around this by adding a normative statement to the spec that says receivers of addressed objects which are not doing full JSON-LD expansion MUST detect the Public collection if it's in the form `https://www.w3.org/ns/activitystreams#Public`, `as:Public` or `Public`. Then senders should know that using other prefixes might not get understood by plain-JSON implementations.

**Comment by cwebber** [comment]
Seems good.  Though adding a MUST here would be a normative requirement yeah?  Whereas I think we can get away with a note if this is clarifying current behavior.  So I'd suggest maybe that we do what you said, but fold it into the note sans the MUST.

**Comment by rhiaro** [comment]
Since as far as we know there are no implementations using anything other than those three options, and we didn't intend any other behaviour than this.. we can probably make it a note "for plain-JSON implementations" since if implementations are doing proper JSON-LD handling this will never come up.

**Comment by cwebber** [comment]
Okay, I updated the text to mention <code>Public</code> and also the "for plain-JSON implementations" text.  Looks good?

**Comment by puckipedia** [comment]
Sounds good, though I'd swap as:Public and Public as the latter will happen more often, probably

**Comment by nightpool** [comment]
I'd like this to be re-opened. The ActivityStreams spec says

```
Relative IRI (and URL) references SHOULD NOT be used within an
Activity Streams 2.0 document due to the fact that many JSON
parser implementations are not capable of reliably preserving
the base context necessary to properly resolve relative references.
```

Are we saying that this is different for AP? As a plain-JSON consumer, changing this to a potentially unbounded number of Public collections I would need to handle is really discouraging and feels like it goes against the spirit of ActivityStreams' JSON-LD compatibility.

**Comment by puckipedia** [comment]
That's another issue, that quote is talking about IRIs in e.g. `object`, `actor`, etc. being relative to the object itself.

This is actually an interesting issue. `Public` has just been defined in the AS context to be shorthand for the entire public collection ID. And your worries only apply if the producer uses a different context than the default. But in that case, there's nothing stopping them from defining `actor` to mean `attributedTo` and vice versa. So you'll have more worries than just the Public colrection. TBH, my suggestion would be, even if you /want/ to do just JSON, run it through a JSON-LD compactor first, with a context you trust (e.g. the same one you use on outgoing messages), to ensure the message conforms to your expectations.

**Comment by cwebber** [comment]
@nightpool this is indeed a different issue.  `(as:)Public` always means the same, global uri, `https://www.w3.org/ns/activitystreams#Public`.  It maps there through the context to the *same* URI every time, and we're saying that even if you're not checking the json-ld context this is the case.

The section you quoted is talking about relative URIs like "/foo/bar.txt" or "#blahblahsomefragment" or "../~Joey/".  What this is saying is if you had resolved the above as relative URIs within the context of `https://foo.example/users/~Alyssa" these should all be remapped to `https://foo.example/foo/bar.txt` `https://foo.example/users/~Alyssa#blahblahsomefragment` and `https://foo.example/users/~Joey` respectively.  That requires that you both a) keep the context of what URI you fetched this from around along with b) being able to identify that this is indeed a relative URI you're talking about... not always easy, and it would be totally different if we fetched the object from somewhere else.

Whereas this issue is about `Public` / `as:Public` always mapping to `https://www.w3.org/ns/activitystreams#Public` in the addressing fields no matter where you had retrieved the ActivityStreams object from.

Does that make sense?  Do you see how that is different from the issue being raised here?

**Comment by nightpool** [comment]
Ah yeah I was tripped up by the overloading of "context" there. Makes sense.
