### ISSUE TITLE
Implementation Report docs / legacy should clarify preferred submission method

### ISSUE THREAD

**Issue by tantek** [w3c-social/activitypump#273]
It appears it is unclear how to properly submit an implementation report for ActivityPub.

E.g. thread https://github.com/w3c/activitypub/pull/272 (cc @snarfed)

At a minimum w3c/activitypub should have a README.md that points to the latest spec and how to file an implementation report.

In addition https://github.com/w3c/activitypub/tree/gh-pages/implementation-reports should also have a README or something indicating how to file an implementation report, as currently it looks like you should fork TEMPLATE.md and submit a pull request (like the above pull link).

**Comment by cwebber** [comment]
I deleted the legacy implementation-reports directory and added [a README](https://github.com/w3c/activitypub/blob/gh-pages/README.org).  The current recommendation for ActivityPub is to use the test suite to generate the implementation report and then just file an issue in this issue tracker.

Technically the implementation reports are [hosted here](https://gitlab.com/dustyweb/activitypub.rocks/tree/master/reports) but I'm not sure it's worth linking people to that since I've been putting them up there myself after people submit reports.

**Comment by cwebber** [comment]
I think that closes this but let me know if you think otherwise.
