### ISSUE TITLE
Is 'liked' property a SHOULD or a MAY?

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#276]
Section 4.1 says: "Implementations SHOULD, in addition, provide the following properties: ... liked..."

Section 5.5 says: "Every actor MAY have a liked collection."

**Comment by evanp** [comment]
Other properties that are SHOULD in section 4.1 are also SHOULD in their call-out sections, AFAICT.

**Comment by cwebber** [comment]
I suppose it ought to be a MAY.  Not everyone wants to expose what they've liked.

The upside is that reducing this from SHOULD -> MAY also is probably not considered a normative change by the rules we've followed since a relaxed requirement will mean that conforming implementations are still conforming.

**Comment by cwebber** [comment]
Done in 2a0e721.
