### ISSUE TITLE
Content type for posts to outbox

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#279]
Section 6 says,  'clients [...] MUST make an HTTP POST request to to this URL with the Content-Type of application/ld+json; profile="https://www.w3.org/ns/activitystreams".' 

We should prefer or at least allow the application/activity+json media type defined at https://www.w3.org/TR/activitystreams-core/#media-type

**Comment by akuckartz** [comment]
Why? Please require or prefer the JSON-LD media type.

**Comment by nightpool** [comment]
as a plain text consumer, I would strongly support moving towards the activity+json media type. No modern web framework has built-in support for profiles on media types.

**Comment by cwebber** [comment]
So I'd prefer application/activity+json also, but unfortunately switching the preferred content-type would be a hugely normative change at this point.  I agree that I'd prefer it... it's important to remember that we ended up with this being the preferred content-type because of extensive conversations with Linked Data Platform implementers which pointed out that they could already accept application/ld+json with a profile at no extra work but it would require further tooling to support application/activity+json.  Those conversations happened quite a ways back, and I don't think we have enough time to revisit them given that we're voting to go to PR tomorrow.

But what we can do is go the "robustness principle" route and and put a MAY on the server end to allow application/activity+json.  In fact we do this with Server-to-Server interactions (except that it's a SHOULD not a MAY... but I'm afraid a SHOULD would be normative at this point).

So how about the following:

``` diff
diff --git a/index.html b/index.html
index 12818d0..fcbf289 100644
--- a/index.html
+++ b/index.html
@@ -1317,6 +1317,10 @@
 	their <a href="#actor-objects">profile</a> and then MUST make an HTTP
         <code>POST</code> request to this URL with the Content-Type of
         <code>application/ld+json; profile="https://www.w3.org/ns/activitystreams"</code>.
+        Servers MAY interpret a Content-Type or Accept header of
+        <code>application/activity+json</code> as equivalent
+        to <code>application/ld+json; profile="https://www.w3.org/ns/activitystreams"</code>
+        for client-to-server interactions.
         The request MUST be authenticated with the credentials of the user to
         whom the outbox belongs.
         The body of the <code>POST</code> request MUST contain a single
```

**Comment by cwebber** [comment]
> we ended up with this being the preferred content-type because of extensive conversations with Linked Data Platform implementers which pointed out that they could already accept application/ld+json with a profile at no extra work but it would require further tooling to support application/activity+json

Oh and it allowed us to achieve interop with Linked Data Notifications too... no small feature :)

**Comment by cwebber** [comment]
@evanp are you okay with the change I put up above?  I think it would allow for the option but it wouldn't be a normative change, which seems like the best we can do right now.

**Comment by evanp** [comment]
Sounds good. The AS2 spec says they're supposed to be equivalent:

```
Because Activity Streams 2.0 can be considered a restricted profile of JSON-LD,
Implementations SHOULD consider the
`application/ld+json; profile="https://www.w3.org/ns/activitystreams"` media type 
as being equivalent to `application/activity+json`. 
```

Since they're supposed to be equivalent, I don't think this should be a normative change. If it's a big hassle, leave it as-is. But I'd at least suggest a note. People are going to use the AS2 content type for sending AS2, and implementors should be aware of that.
