### ISSUE TITLE
Actor formerlyKnownAs property

### ISSUE THREAD

**Issue by kaniini** [w3c-social/activitypump#300]
It would be nice to get a "formerly known as" property on actors that points to the URL of the actor object the actor was previously using.

The main rationale is so that if an account migrates from one server to another, they can just send out new Follow requests with the "formerly known as" property, and the receiving servers could, for example, automatically ACK or re-follow them back.

This would also require a "now known as" object on the Actor or Tombstone at the previous location, so that it is verifiable.

Ideally, the act of sending a Follow activity (or perhaps a new activity of this type) would be to swap the actor relationships as appropriate (perhaps keeping the old relationships too).

This is helpful toward making nomadic identity more seamless.

**Comment by ClearlyClaire** [comment]
This seems reasonable to me, with the limitation that it doesn't seem to support “merging” multiple former accounts.
Mastodon currently uses a `movedTo` attribute on actors for the purposes of the “now known as” object, but currently doesn't implement anything for the other half of the process.

Tagging @Gargron as he was discussing a different proposal to fix the same issue a few days ago.

**Comment by kaniini** [comment]
yeah, `movedTo` would be perfectly fine for this.

However, thinking about it more, I want to suggest the idea of just using a single `alsoKnownAs` list and keeping `movedTo` as it's original purpose.  Authorization can be proven by checking for cyclical references between the `alsoKnownAs` lists.

I intend to blog more about it, this weekend.

**Comment by kaniini** [comment]
I updated the title of this issue to reflect the more generic concept of using an `alsoKnownAs` object.

**Comment by cjslep** [comment]
Has there been any thought as to how to prevent account or follow hijacking? A rogue site that decides to send out bogus Follow requests with their actor model falsely claiming `alsoKnownAs` would be a significant security problem if systems decided to blindly take automated action.

**Comment by ClearlyClaire** [comment]
@cjslep “alsoKnownAs” would tell that an actor is ok to be a “new identity” for other actors. A corresponding “movedTo” on the originating actor would be needed for any kind of automated action.

**Comment by cjslep** [comment]
Understood, thanks for clarifying.

**Comment by kaniini** [comment]
You would check actually for cyclical reference on `alsoKnownAs`.  `movedTo` would be kept as it's original purpose.  But basically, both actors would refer to each other in the `alsoKnownAs` lists.

**Comment by cwebber** [comment]
I think Mastodon actually rolled out such a property.  @gargron or @nightpool, is that correct?

**Comment by nightpool** [comment]
I believe we just have movedTo. The eventual plan was to supplement it on the moved to account with a list of pre-signed "Migrate { Account }" messages from the "primary" account which could be generated ahead of time. We haven't had time to come back to the feature since then though.

**Comment by Gargron** [comment]
@nightpool I was actually thinking we could avoid messing with multiple signatures on a single message if the servers that receive a Move activity check the moved-to account for something like this proposed alsoKnownAs property, that would simplify the implementation (just gotta be careful not to DDoS the moved-to server when 2,000+ servers check the actor JSON)

**Comment by nightpool** [comment]
Ah, sure. That's probably much more simple then trying to figure out the whole loop-checking thing, and it doesn't require any setup ahead of time (except exporting your key)

**Comment by Gargron** [comment]
Why key export? This procedure can happen between two entirely separate accounts, no?

1. aliceOld sends move request to aliceNew
2. aliceNew accepts move request and puts aliceOld into alsoKnownAs
3. aliceOld sends move activity to followers
4. Each follower checks aliceNew for presence of aliceOld in alsoKnownAs

I just am not entirely sure how the first two steps should be expressed. Clearly what gets sent to followers in step 3 is a Move activity where target is the new account. But would the same format suffice for step 1? And would step 2 be an Accept activity of the Move activity? Or would step 1 more eloquently described by an Offer activity of a Move activity or something similar?

**Comment by nightpool** [comment]
Right i'm saying in the event that your server goes down and you didn't prepare for it, then you have a recourse if you exported your key. 

Maybe this is a bad assumption (that people might export their keys but not have time to set up a more complicated backup account). As I see it, we currently have three proposals for how stuff should work from a UX perspective.

1. Kaniini's, which is "Actors set up backup accounts ahead of time, but can migrate when the first account goes down as long as the information gets federated". This has the benefit of not requiring signed requests as long as everyone who could ever want to verify the authenticity of the move has a copy of the profile from the original server.

2. Yours, which is "Actors can send move requests back and forth, but this requires both servers to be up". This has the benefit of being more idiomatic to activitypub, and being maybe simpler/more intuitive for users, but doesn't work when instances just disappear.

3. Mine, which is "you import an old account key into your new instance, and then it generates all the payloads necessary and sends them out." This would use the same federation methods as the gargron's proposal, but could (optionally?) be handled entirely by the new server in case you don't have access to the old one and didn't think of somewhere to go ahead of time. All it would require is information we already have in the account export.

**Comment by Gargron** [comment]
@nightpool So would that work like... you receive a payload from a new user, on behalf of old user, but you verify the new signature with the old key..? I feel like that might be a bit unreliable given that any account can switch keys at any time and we just accept the new key, a behaviour that was required because people would sometimes lose or wipe their DB and wonder why their new accounts are rejected everywhere

**Comment by nightpool** [comment]
> given that any account can switch keys at any time and we just accept the new key

I mean, that doesn't ever happen except when the instance loses all of it's data, right? And only if they're serving the new key from the same authoritative actor. I dunno. I think given the two minor instances we've had go down without any warning in the last 2 months, we need to do something beyond "well, if both servers aren't up then you're out of luck"

**Comment by Gargron** [comment]
@nightpool Unless you go the full nomadic identity route where you duplicate *all* data including followers to a backup account, how would the backup account know who to send the activities to to restore the followers?

**Comment by nightpool** [comment]
hmm i guess we only ACTUALLY export following, huh. followers.csv?

**Comment by cwebber** [comment]
There are a couple ways forward that support the key export stuff:

1. Your key is uploaded to your profile, and previously I saw you on https://deadsite.example/~userfoo/ and got your profile.  I saw that was your key and I "exported" it to my home computer.  Once your server went down, I was able to upgrade to a new server and re-upload my keys, thus signing a message saying "this is my new location!" and sending that to all my followers.  This is doable but we need to have clients have direct support for this functionality with just a few taps to make it feel "natural", otherwise it'll be permanently awkward for users.  However, it doesn't really "move" your posts over to the new namespace.
2. Nomadic identity where your key fingerprint is your *real* username.  Your post *claims* it used to be at some url, but it's the fact that it's signed by your key that makes it really your post.  This also means you can move that post somewhere.  However, if someone shows up late, you can claim you posted it somewhere else and lie about it, and they won't know (imagine your domain got taken over by someone else).  Worse yet: you can't rotate your keys!  encryption keys have historically only been securely usable for about 10 (maybe 15) years.  I hope the fediverse lasts longer than that.  I've had my email address for much longer than that.
3. Nomadic identity but where you can rotate your keys.  DIDs are heading down this direction.  You may also be able to do it by pushing around certificates saying "here's my updated key" that you signed with the old key.
4. Nomadic identity with rotateable keys and also a namespace that's yours for life, where you can move your content and that stuff will still be clearly part of your namespace: DIDs are also heading down this path, but I'm afraid that we can't wait on DIDs.  IPFS also does something similar, but you can't rotate your keys there.

IMO 1 is feasibly achievable today, it just requires coordination with clients so that *click* backup my key and *click* upload this key to my new account I'm transferring to.  As long as you hold onto a device you've done that on, you can move, and do a limited amount of the ideas above.

**Comment by Gargron** [comment]
@cwebber Could you comment on my AP activities semantics?

**Comment by kaniini** [comment]
hi,

i kind of like @nightpool's idea of exporting the key.  you could use that in combination with the old actor URI as a sudo-like mechanism without having to check the references.

perhaps a hybrid approach of both my idea and theirs is the way forward?

**Comment by Gargron** [comment]
Are there any updates on alsoKnownAs property per se? If we establish movedTo<->alsoKnownAs between two accounts we could already make followers switch over, at least in those cases where the old server is still online.

**Comment by kaniini** [comment]
i'm okay with the cyclical reference concept, but would like to see key export too.  if you go ahead with movedTo<->alsoKnownAs, i'll implement that in Pleroma (but probably not until after 1.0, we are trying to concentrate on knocking out 1.0 blockers right now)

**Comment by nightpool** [comment]
the cyclical reference is nice because it lets us embed a signed object
later if the server goes down, without changing the structure at all.

**Comment by ap-socialhub** [comment]
This issue was moved to https://socialhub.activitypub.rocks/t/actor-alsoknownas-property/184

**Comment by evanp** [comment]
So, this is a very big issue on the fediverse, and we don't have good standard documentation. This conversation has been great, but issue #357 is a more general conversation about migration. I'm therefore going to close this issue in favour of that one (even though it was submitted later), and we can continue the migration discussion there.
