### ISSUE TITLE
How to implement "relocation" message?

### ISSUE THREAD

**Issue by annando** [w3c-social/activitypump#322]
I'm currently implementing AP for Friendica. Some things are unclear.

DFRN - or own protocol - does support a so called "relocation" message. This message is sent out when a user moves his/her account to another server. The message is sent from the new account. We keep the private/public keypair upon moving, so that our receivers can check that we are who we pretend to be. We don't send the old profile url. We only send the new profile data.

How could this be done with AP?

**Comment by trwnh** [comment]
In theory: there is a Move activity https://www.w3.org/TR/activitystreams-vocabulary/#dfn-move
In practice: Mastodon uses a `movedTo` field extension https://github.com/tootsuite/mastodon/blob/78ed4ab75ff77d7cba60d478aa1f45d1c104785d/app/lib/activitypub/adapter.rb#L12 described here https://gist.github.com/nightpool/21fb737babb2f8714d911236e21b05e7

I'm not sure if there's a formal ActivityPub way of doing things yet that's different from what Mastodon does, but it's worth noting that `movedTo` has the expectation that you should NOT take any automatic actions, since the two Actors are still considered separate entities.

**Comment by annando** [comment]
At Friendica the behaviour is different. The old account isn't valid after this action.

**Comment by jaywink** [comment]
Related: https://github.com/swicg/general/issues/1

**Comment by evanp** [comment]
This is an important issue for everyone using ActivityPub. It's important enough that we have a dedicated taskforce working on the topic right now. https://github.com/swicg/activitypub-data-portability is a good place to find important information about moving people between actor accounts. I'm going to close this issue in deference to that task force.
