### ISSUE TITLE
Review new authorization section in Authentication/Authorization wiki page

### ISSUE THREAD

**Issue by snarfed** [w3c-social/activitypump#394]
Hi @evanp et al! I recently started implementing AP authorization, and it's maybe even less specified than authentication, so I did a bit of homework in https://github.com/snarfed/bridgy-fed/issues/566#issuecomment-1763177133 and wrote up some conclusions in https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization#Authorization . Mind reviewing? Feel free to revise mercilessly. Thanks in advance!

**Comment by silverpill** [comment]
>In those cases, if the activity includes a Linked Data Signature, it can be verified and checked against activity's actor.

I think all references to "Linked Data Signature" should be removed from ActivityPub and related documents, because such thing doesn't exist anymore and it's very confusing for developers. The latest version of the Data Integrity specification (previously known as Linked Data Signatures) uses the term "[data integrity proof](https://w3c.github.io/vc-data-integrity/#dfn-data-integrity-proof)".

See also: https://codeberg.org/fediverse/fep/src/branch/main/fep/8b32/fep-8b32.md

**Comment by snarfed** [comment]
Thanks for looking! Sure, I can do that.

Any other thoughts? Does it match your understanding of the current ecosystem? Did I miss anything?

**Comment by silverpill** [comment]
Yes, the "Authorization" section looks good. Thank you for adding it!

**Comment by steve-bate** [comment]
> I think all references to "Linked Data Signature" should be removed from ActivityPub and related documents, because such thing doesn't exist anymore and it's very confusing for developers. The latest version of the Data Integrity specification (previously known as Linked Data Signatures) uses the term "[data integrity proof](https://w3c.github.io/vc-data-integrity/#dfn-data-integrity-proof)".

Should we create a separate issue for updating the recommendation (in case the SocialWG is rechartered to update it)?

**Comment by silverpill** [comment]
@steve-bate "Linked Data Signatures" are used in descriptions of `provideClientKey` and `signClientKey` endpoints, and for those we have issue #382. I can't find other mentions in ActivityPub spec

**Comment by steve-bate** [comment]
> @steve-bate "Linked Data Signatures" are used in descriptions of `provideClientKey` and `signClientKey` endpoints, and for those we have issue #382. I can't find other mentions in ActivityPub spec

Thanks. That issue/question is a lot less focused than what I had had in mind. BTW, not that this would require keeping that terminology or the related endpoints in the recommendation, but LDS is widely used in the Fediverse for the Mastodon relay protocol.

**Comment by nightpool** [comment]
Not just for relays, Mastodon also uses linked-data signatures to implement inbox forwarding as per AP section 7.1.2

**Comment by evanp** [comment]
I did review. This is a great summary of authorization in AP. Thanks for writing it!

I added a section on addressee access, since I think that's important. We should probably include subsections on some more exotic alternatives; for example [https://codeberg.org/fediverse/fep/src/branch/main/fep/400e/fep-400e.md FEP-400E] for multi-user collections, and admin access (primarily for C2S). But I think we've got a good start here.

**Comment by snarfed** [comment]
Awesome, thanks again for reviewing!

**Comment by snarfed** [comment]
Related, oof, insufficient authorization and origin checks led to a big Mastodon vulnerability disclosed today: https://github.com/mastodon/mastodon/security/advisories/GHSA-3fjr-858r-92rw , https://wedistribute.org/2024/02/mastodon-remote-takeover/
