### ISSUE TITLE
Web Annotation Protocol?

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypump#4]
It seems like there are many similarities between the goals of the Social WG "Federation Protocol" and the Annotation WG "HTTP API for Annotations"

Both are deliverables in the respective WG charters. And both have similar deadlines (Feb 2016 vs Q1 2016 for CR).

At Livefyre, we've implemented both Embedded Experiences (comments, liveblogs, news feeds) and (Social) Annotation on the same service offering, and found there to be more similarities than differences between all these things.

There is currently a WIP Editor's Draft of [Web Annotation Protocol](http://w3c.github.io/web-annotation/protocol/wd/), mostly contributed to by @azaroth42 and @shepazu

Note:
The SocialWG Charter also says "Note that the Working Group may not develop the Federation Protocol into a Recommendation and it may become a Working Group Note." I think the Web Annotation Protocol is a smaller problem than a Federated Social Protocol (see: salmon), so if they can't be worked on together, maybe it's best to see how the Annotation Protocol settles before taking on the Social Federation Protocol? I care about both use cases, and would love web standards for both. Just pointing out one possible future.

I realize this may be controversial, but I'd love to hear from others on pros and cons of trying to specify a single HTTP/application protocol to serve both of these deliverables.

**Comment by azaroth42** [comment]
Hi Ben, all,

On behalf of the Web Annotation WG, we would love to come to an understanding of a single protocol that could serve both groups.  Any opportunity to promote real interoperability between diverse systems is one that should be taken if possible, and discarded only after every effort has been made to reconcile any differences.

The Annotation work, as you can see, has started from the Linked Data Platform as a baseline, and is mostly a very simple profile of it to let systems treat it as a JSON based system rather than an RDF system that provides JSON-LD as one serialization.  From following the discussions on the Social WG list, this appears to be in line with how you're thinking as well.

Federation/Aggregation of annotations is also a use case for us, along with notifications about events such as when an annotation is created or modified.  We were hoping that ActivityStreams 2.0 would be valuable in that space.

We had a F2F meeting last week that has provided some additional feedback on the current ED, and I hope to have it updated next week with those comments.  At that point, I wonder if there would be value in a joint call?  TPAC is still quite a long ways off, but it would also be a good venue for collaboration if both WGs are going to attend.

Many thanks for taking the initiative here!

**Comment by shepazu** [comment]
I strongly agree with the sentiment that there should be only a single protocol/API if possible.

(BTW, I haven't contributed materially to the Web Annotation Protocol spec; that's mostly Rob.)

**Comment by akuckartz** [comment]
:+1:

**Comment by xray7224** [comment]
This is probably best brought up to the WG itself, this being just one of the candidates that might (hopefully) will become the specification the social WG puts out. There are also several candidates up for consideration. I feel this issue would be best discussed there (the WG itself).

**Comment by cwebber** [comment]
I agree with @xray7224.  We should have this conversation.  I'm hesitant to do it on the ActivityPump tracker itself.

There may be ways that ActivityPump and the Annotations group could come more in line.  I would think that the first layer to look at this on would be ActivityStreams 2.0, see where interoperability should exist, and then come around to ActivityPump.  What do you think?  It would probably be welcome to open issues to bring certain *specific* things in line with ActivityPump on this tracker.  But I think the right place for the rest of this conversation is with the working group itself.  Hence I'm closing this!

I do look forward to further conversation though!
