### ISSUE TITLE
Document authorized fetch

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#402]
The Mastodon service has a feature called [authorized fetch](https://docs.joinmastodon.org/admin/config/#authorized_fetch) that requires HTTP signature authentication for any GET request for objects on the server, even if the object is publicly readable. Some other software also supports this feature.

The advantage of this feature is that it can be used to enforce server blocks and user blocks. It gives an authorization model of "everyone except these actors: ...".

We should document this pattern in the Primer to make it easier for developers to interoperate with other servers.

**Comment by trwnh** [comment]
Tagging #339 as tangential to this, since "authorized fetch" is technically a spec violation for the definition of as:Public

**Comment by snarfed** [comment]
Thanks @trwnh!

Also, tangent, it'd be nice to maybe try to rename this to "authenticated fetch," which seems more accurate. Not sure if we're too late there though 😁

**Comment by trwnh** [comment]
to be precise, it's really "signed fetch" since it uses http signatures (cavage draft 08). one could imagine a similar mechanism which works on bearer tokens or pre-shared secrets or what have you. AUTHORIZED_FETCH is just the environment variable that mastodon uses to refer to the feature

edit: this is a bit pedantic to be sure but "authorized fetch" to me evokes a sense of using the http `Authorization` header whereas "signed fetch" signals that we are using the http `Signature` header.

**Comment by nightpool** [comment]
In this case, "authorized fetch" is referring to the fact that the origin
server has enough information to make an authorization decision. (e.g., to
enforce blacklists)

**Comment by cristianolongoodhl** [comment]
please consider that HTTP Signature is not a Recommendation, but just a dead draft

**Comment by tesaguri** [comment]
> please consider that HTTP Signature is not a Recommendation, but just a dead draft

Could you elaborate on the phrase, <q>a dead draft</q>? It's true that HTTP Message Signatures is an IETF Internet Draft rather than being a W3C Recommendation, but its [latest draft][draft-ietf-httpbis-message-signatures-19] is marked as Active.

[draft-ietf-httpbis-message-signatures-19]: <https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures-19>

**Comment by trwnh** [comment]
HTTP Message Signatures is not the same as HTTP Signatures. The active draft replaced the older Cavage draft that the fediverse currently uses. The Cavage draft is what is considered "dead".

**Comment by snarfed** [comment]
Understood! The goal here isn't to specify anything normative anywhere, it's just to document the fediverse's already widespread existing usage of HTTP Sigs, especially the subset of instances that currently require them on object fetches. We can definitely mention loudly in that documentation that that the Cavage HTTP Sigs standard is "dead," or whatever the most appropriate term is.

**Comment by snarfed** [comment]
I took a stab at documenting authorized fetch and instance actors as they stand today in the wild. Feedback is welcome! https://www.w3.org/wiki/index.php?title=SocialCG%2FActivityPub%2FAuthentication_Authorization&type=revision&diff=116867&oldid=116776

**Comment by evanp** [comment]
Since this ticket was opened, the SocialCG decided to start a whole Report on ActivityPub and HTTP Signature. We now have a very useful draft report at https://swicg.github.io/activitypub-http-signature/ including a whole section on Authorized Fetch at https://swicg.github.io/activitypub-http-signature/#authorized-fetch . I think this resolves the issue, and since I'm the original requester I'm going to use my prerogative to close the ticket.

**Comment by evanp** [comment]
I added a new issue to make sure the AuthC/AuthZ primer page is synched with the HTTP Signatures report. #435
