### ISSUE TITLE
Sharing a post routes around a server block

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#405]
Scenario: server1, server2, server3

server1 blocks server3.

b@server2 follows a@server1

c@server3 follows b@server2.

a@server1 Creates Note server1/note/1

b@server2 Announces Note server1/note/1

Full copy of Note server1/note/1 delivered to c@server3 by server2 inside the Announce activity.

This routes around the server block.

**Comment by tesaguri** [comment]
Is there a real-world example of a server implementation that embeds the content of unsigned remote Note objects into Announce activities?

That doesn't seem to me to make much sense since recipients of the activity would need to fetch the original Note to verify its content anyway. I believe it would be a vulnerability of server3 if it trusts the embedded object shared by server 2 without consulting server1.

And I think it's a commonly implemented precaution to disable signing if the server opts into "authorized fetch." At least, that's how Mastodon handles the Linked Data Signatures (<https://docs.joinmastodon.org/admin/config/#authorized_fetch>).

**Comment by snarfed** [comment]
Hmm! @evanp minor nit, does AP currently specify server-level `Block`s? https://www.w3.org/TR/activitypub/#block-activity-outbox seems to only describe actor to actor. Granted, your question may still apply at actor level in spirit at least.

**Comment by snarfed** [comment]
> That doesn't seem to me to make much sense since recipients of the activity would need to fetch the original Note to verify its content anyway. I believe it would be a vulnerability of server3 if it trusts the embedded object shared by server 2 without consulting server1.

True! This kind of authorization is not clearly specified in AP, but we came to broadly the same conclusion in https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization .

LD Sigs/data integrity proofs could be one possible approach here. Some servers like Mastodon already include LD Sigs in inbox-forwarded activities as a way to prove the authenticity of embedded objects that they didn't originate: https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization#Data_integrity_proofs_.2F_Linked_Data_Signatures . Refetching the object from its source does provide authorization, but if we wanted to optimize network traffic, embedded signatures could be one solution.

**Comment by cristianolongoodhl** [comment]
I think this is a confidentiality issue, not a integrity one. And, message signatures does not protect a message from disclosure, it is just a proof of its integrity. However, I think that avoiding to report the full object in activities is a good practice for several reasons, including the case mentioned before.

**Comment by snarfed** [comment]
Agreed! "Data integrity proof" is just the name of the newer variant of LD Signatures. It was part of answering @tesaguri's question of whether/when activities include full contents of remote objects, not a proposal for confidentiality or access control.

**Comment by ThisIsMissEm** [comment]
@evanp is currently expanding the ActivityPub primer page for Announce Activities

**Comment by evanp** [comment]
I updated to note the recommendations on embedding or referencing objects:

https://www.w3.org/wiki/ActivityPub/Primer/Announce_activity#Inclusion_of_the_shared_object

I'm going to mark this pending closure.

**Comment by evanp** [comment]
Looks like this is done, and as the original poster I am satisfied.

**Comment by ThisIsMissEm** [comment]
@evanp on this, would the primer page also feed into next version? I think in the ActivityStream Vocabulary we could certainly update the example to show best practices, instead of embedding, and also reference the primer page on this activity type.

https://www.w3.org/TR/activitystreams-vocabulary/#dfn-announce
