### ISSUE TITLE
Change community domain name 

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypump#421]
Today the queer.af fediverse server run by ActivityPub co-author @erincandescent was disabled by the Taliban government which runs the Afghan top-level domain .af.

Erin is moving on and my understanding is that she doesn't want to continue running the server and that most users managed to move before the shutdown. So, this is not of immediate concern.

However, we need a way to move a full community from one domain name to another, for this and other reasons.

A similar use case happens when organizations set up a "test.example.com" Mastodon server, sign up a few dozen users, and use it for a month or two. When they decide to make it "production.example.com" or whatever real domain they want to use, they find out that all their previous content and connections are lost. Not good!

For #DataPortability let's figure out a way to change a server's domain name.

**Comment by nightpool** [comment]
Is this a particularly different use-case then just migrating all of the
users on the domain one-by-one?

**Comment by neptuwunium** [comment]
From my understanding of the issue this would be a record rewrite rather than a migration indicating that the server is still the same but the IRI origin host has been changed. 

I feel like this should be part of a larger system introduction where individual accounts can be rewritten. This would also allow for accounts to rename themselves rather than migrating to the same instance (which is silly, in my opinion.) Though, I would imagine the current system works as it does for a reason (hopefully!)

Though for support it could be hit or miss. We already see some people playing around with rewrites by introducing a `.well-known/webfinger` implementation on domain A (i.e. `example.org`) that points to domain B (i.e. `social.example.org`) allowing for `jane@example.org` to resolve! Some implementations can't handle this well and instead treat it as a broken mention.

In realizing this, I believe there should be some system in place to indicate if the server supports this extension at all (perhaps a shared endpoint, or an array of well known keywords in nodeinfo.) This would allow the server to fall back to other, more stressful solutions (i.e. sending a migration for every single user.)`

**Comment by evanp** [comment]
@nightpool I think it's a similar use case except for scale. Reporting hundreds of thousands of account moves rather than a single server move seems kind of wasteful and error-prone. However, that's one implementation.

**Comment by evanp** [comment]
Because this is so focused on data portability, I've moved it to swicg/activitypub-data-portability#10. I recommend people follow up there. I'm going to close the ticket.
