### ISSUE TITLE
Outbox stream having ALL objects seems unsustainable

### ISSUE THREAD

**Issue by dissolve** [w3c-social/activitypump#63]
Having the endpoint require that it contains every object ever published seems rather unsustainable.  Does this include deleted items?  Why can a implementation not limit this to only the last N?

Would a multi-user system be basically giving a firehose (of public posts) to everyone?

**Comment by wilkie** [comment]
Looks like the outbox is defined per Actor (as opposed to a giant firehose for multi-user systems) and you yield a Collection. In AS2, a Collection can consist of CollectionPage objects and not every object. In that case, you would send however number of items as a CollectionPage in the 'first' property of a Collection and that can be implementation-defined. A client could then use that collection page to find the rest of the objects on its own time.

Therefore, only technically (and not literally) does the outbox contain every activity. So, I'm assuming clarity in the outbox section would help make that better understood?

**Comment by dissolve** [comment]
It's also a question of MUST, SHOULD, or MAY?   Can my implementation drop older objects and not include them at all?   Some days social systems will only let you go back a limited amount of time / number of posts.

**Comment by wilkie** [comment]
Hmm. Anything not specified in the specification would be implementation-defined. I'd think whether or not to persist activities is ultimately an implementation decision. These comments seem a bit pedantic, in that context, if explicitly specified. That is, a solution may just be to simply provide the blanket implication: if you don't want posts in your outbox, don't include them in the Collection.

So, I'd say: it SHOULD contain "...every object that the user has ever published, subject to the ability of the requestor to retrieve the object" and allow that implication.

**Comment by dissolve** [comment]
Adding SHOULD there would certainly be a solution.  Probably good to clarify it must be per user, never shared.  Also one day the same thing applies to outbox... G+, linked in, github, and I believe Facebook only maintain notifications for so long... After that they drop them.

Does it need to even be SHOULD though?  What exactly is the benefit of maintaining it past a month for example?

**Comment by wilkie** [comment]
It is an implementation detail that depends on what a particular person/service needs or what resources a server might have. It doesn't even particularly hurt to page a collection of all activities, or even just Create activities, on the fly. A very robust activitypump implementation may write a sophisticated policy for choosing what stays and what goes, certain activity types may live longer than others, but this would be wrong to explicitly specify. Also, if my site were only a blog, I might make posts infrequently and it would be completely reasonable to have all of the objects in the outbox. When a situation is strongly a "it depends", this is the place for SHOULD.

**Comment by dissolve** [comment]
If it is strongly "it depends". I would say that's a MAY, not SHOULD.   SHOULD is more like strongly recommended but you can break that if you must. 

Paging is completely irrelevant to this.  

Right now the spec says it contains every post ever.... Which reads as a MUST.

**Comment by cwebber** [comment]
Paging isn't irrelevant because it's what makes having such a series possible.  You aren't getting all the information at once.  As Wilkie pointed out, it's per actor, not per system.

@dissolve, could you clarify more exactly *why* you think this is unsustainable?  Is it primarily a storage concern, that keeping all this information around forever is a bad idea?  Or is it privacy, that it's dangerous to keep certain information around forever?  (That seems to be the ephemeral/transient messaging concern we discussed at the face to face.)

It could be that certain implementations could show a truncated version of the number of activities present on a system, so that some bot does not page forever to your entire system, or whatever the concern is.  It would be useful to know exactly what the concern is.

As it is, the current specification implies that you do have to keep at least some minimal version of activities around forever anyway.  In both pump.io and mediagoblin (well, our git master branch at present), if you delete an object, a "tombstone" object is put in its place with minimal information.  This is because of the verification requirement.  So one question is, if you have to keep objects/activities around forever, is it any worse to have to make them available via an outbox forever?

**Comment by wilkie** [comment]
Let's avoid the SHOULD/MAY distinction. "MAY contain every object" doesn't make that much sense. It's kind of a tautology. And it's better to try to word in a MUST. The 'every object' is getting in the way of that, so remove it.

How about "An outbox is a collection of objects an actor has published. An outbox MUST contain only the published objects the person requesting can view. An outbox MAY omit objects for any reason, for instance applying a cap to how many objects are retrievable."

**Comment by dissolve** [comment]
@cwebber. I should say paging is irrelevant in that it is obviously possible.  
It was mostly a concern of processing a log that goes back indefinitely.   If I rewrite my system i have to port everything in to an outbox.  But since you brought it up, privacy is actually an issue too.  Discoverable via outbox and discoverable via source URL are very different.  I publish publicly verifiable data that I don't include in a public feed. Replies that I don't publish on my main feed for example, anyone can see the response if they discover it via the message I commented on, but I don't want to publish it for others who follow me.   

@wilkie I agree MAY contain every object doesn't make much sense.  I think that's a sensible wording.

**Comment by cwebber** [comment]
Okay, so maybe we should examine what the purpose of the outbox is.  Generally it's being polled by some entity for the activities that person has permission to access (so the stream may be different depending on who's polling it).  Most distribution, ideally, does not get read via this polling, it gets handled by the more asynchronous posting of activities to the appropriate recipients mechanism.  So you're mostly going to check the outbox because you want to look at what's in there maybe because you just want a localized view, or because you want to see if you missed something because your server was down, or because you just subscribed to someone and want to see what's up.

I brought up the "you have to keep things around anyway for verification" because it helps inform "what's the problem anyway?" part of this discussion.  However, even in the current system, that's not where verification occurs.

Here's another question: what breaks if you *don't* end up continuing to post old activities to your outbox?

As far as I can tell, reading from the outbox exists so that others can "catch up" on what you've been doing.  If you don't end up publishing certain information in there, it's probably fine.  I don't think it'll break anything.  So I think this may be up to the implementer.  So we should maybe explain that this is where users should make a viewable stream of their recent activities, but it's up to the implementation to decide how back they want to go (forever is likely a good idea for archival purposes, but not required).

@evanp may point out that I am totally wrong here in this analysis, I'm not sure.  But that's my understanding.

@dissolve @wilkie What do you think?

**Comment by dissolve** [comment]
Makes sense to me, I don't see any reason for outbox to require all items, especially if the key use case for it is in that initial subscription to a person's updates.  :+1:

**Comment by cwebber** [comment]
Updated in d39af6d.
