### ISSUE TITLE
Discovery of collections/streams

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypump#71]
AP defines some arbitrary `Collections`, the concept of streams, and the specific `inbox` and `outbox` streams. But it's not clear how to point to say all of my collections or streams from my profile. 

The arbitrary Collections require arbitrary properties (`likes`, `followers`) to point to them. It would be nice to make this generic (maybe there's an existing rel value, or `stream` or `feed`) which could be used for any and all streams I wish people to be able to discover, without having to publish them all in my main `outbox` feed. And then have the Collections describe themselves, eg. through the `objectTypes` property (which would be `Like` for the `Likes` collection).

Admittedly if a client is looking for `followers` it's easier for it to just check for the `followers` property than dereference _every_ link out to a stream it finds and check all the types. So to optimise we could just nest the `objectTypes` (where applicable (related: https://github.com/w3c-social/activitypub/issues/53); or any other useful describing feature), ie. go from:

```
"followers": "https://example.com/~alice/collections/followers",
"likes": "https://example.com/~alice/collections/kittens",
```

**to**

```
"stream": { "id": "https://example.com/~alice/collections/followers", "objectTypes": as:Actor } ,
"stream": {"id": "https://example.com/~alice/collections/kittens", "objectTypes": as:Like } ,
```

_However_ I'm all for 'sensible defaults', so if you wanted to keep a handful of arbitrary properties for convenience I think that's fine, so long as there is _also_ a clear mechanism for discoverability of any other feeds from a profile (and no _obligation_ to implement these defaults, a la https://github.com/w3c-social/activitypub/issues/69).

(cc. @dmitrizagidulin who sparked this train of thought)

**Comment by cwebber** [comment]
So this is really interesting.  I think @evanp would have to weigh in on this.  I might be okay with there being other ways to capture supplementary streams, though I think I'd prefer to have the primary streams where they are, but that may be a Pump API backwards compat / vision sense of things.

I'm not sure capturing the objectTypes really clearly articulates what something _is_.  "followers" are mostly as:Actor, but so is "following".  The API needs a clear way to articulate that.

Maybe something like:

```
{"streams": [
    {"id": "https://example.com/~alice/collections/kittens",
     "objectTypes": as:Like}}
```

What does it get you though?  Can you articulate some scenarios where this would be _useful_?  I'm having trouble imagining where this would show up in a user interface for example.

I think this needs real use cases in order to justify being added.  It might make things more complex.

**Comment by cwebber** [comment]
F2F chat: So we will have special API specific collections, like likes and followers and inbox, but streams should be supported as a general bucket for interesting collections.

**Comment by cwebber** [comment]
Added.
