### ISSUE TITLE
Split the specification up into more implementable sections

### ISSUE THREAD

**Issue by tsyesika** [w3c-social/activitypump#79]
The current spec is quite large and it's going to be pretty difficult for a single person to take this and implement it over a weekend, it also could be the case that a social network might not want a lot of the things in the specification. It would be good to split the specification up into easier pieces, not require all pieces to be implemented.

This could in the future even be split into different specifications and ActivityPub simply can refer to them.

This was brought up by @rhiaro

**Comment by cwebber** [comment]
Evan [submited this graphic](https://www.w3.org/wiki/Socialwg/API/Layers) about how to break things up, and Amy did an example of breaking things up too.

**Comment by cwebber** [comment]
Amy also would prefer that subscription based delivery be broken out separately from delivery because of users specifically addressing someone.  Amy agrees that the receiving of activities remains the same whether you're being delivered because of addressing but on the sending side there's a difference between whether you have to supply functionality for subscription or not.

**Comment by cwebber** [comment]
The group is strongly leaning towards splitting into two specs, so probably that will be done but up to editor discretion as to whether to refactor within existing document or split into two immediately.  Could be named ActivityPub and ActivitySub (or ActivityDist, ActivityFed).

**Comment by cwebber** [comment]
This has been done; we're keeping things in one document but we now have clear "client to server" and "server to server" sections.
