### ISSUE TITLE
mediaEndpoint -> media-endpoint

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypump#94]
To match [micropub](http://micropub.net/draft/#media-endpoint).

(disclaimer: biased in preferring hyphens to camelCase. This month, anyway).

**Comment by elf-pavlik** [comment]
In Javascript and possibly other runtimes, hyphens don't work well when accessing object properties using 'dot notation'

``` js
let uri = actor.mediaEndpoint
```

works fine but with properties using hyphen in name one needs to use array notation

``` js
let uri = actor['media-endpoint']
```

**Comment by cwebber** [comment]
The rest of ActivityStreams' property names are mixedCase, so I think we should leave it ias-is.

**Comment by melvincarvalho** [comment]
Also the JavaScript Standard that I think many people use require camel case (as opposed to underscores or somethings else).  JS variables with a dash will throw an error as the minus sign is an operator in most languages.  It's a fairly terrible idea to pass around messages with properties that include minus signs, because it often will require another level of translation in the code.

Crockford explains that not needing to such a translation is one of the reasons JSON took off.  ie Hyphens should be considered harmful.

http://www.youtube.com/embed/kc8BAR7SHJI
